### PR TITLE
fix: interstitial screen release review fixes

### LINKED ISSUE #7699: Interstitial screen release review issues
Fix the issues from[ Interstitial screen release review](https://github.com/carbon-design-system/ibm-products/issues/7607)

- 2 a11y violations in accessibility tab needs to be fixed
- interstitialAriaLabel naming convention to be more generic ?? agree naming to ariaLabel
- aligning isOpen -> open to match tearsheet ??
- Add devtools attribute to sub components (header, body, footer)
- Pass rest props in both footer and header sub component
- Export types for sub components from `InterstitialScreen/index.ts`
- Ensure all types from base IntersitialScreen and it's sub components are exported
- Revisit if it is absolutely necessary to use `!important`s in `_interstitial-screen.scss`
- A block class variable is defined in the based and all sub-components, to clean it up a little bit you could just export it from the based and not have to re-define it 
- The button appears to be overflowing its container by 1 px. in some variations.

Image

### PR DESCRIPTION
**Pull request by amal-k-joy**
Closes #7699 

Interstitial screen release review issues

- 2 a11y violations in accessibility tab needs to be fixed : _1 is fixed. Other one is false positive throwing for scrollable_ elements
- interstitialAriaLabel naming convention to be more generic ?? agree naming to ariaLabel : _done_
- aligning isOpen -> open to match tearsheet ?? :  _done_
- Add devtools attribute to sub components (header, body, footer) :  _done_
- Pass rest props in both footer and header sub component :  _done_
- Export types for sub components from InterstitialScreen/index.ts :  _done_
- Ensure all types from base IntersitialScreen and it's sub components are exported :  _done_
- Revisit if it is absolutely necessary to use !importants in _interstitial-screen.scss : _done. Removed most , but some are required to override compose modal spacings_
- A block class variable is defined in the based and all sub-components, to clean it up a little bit you could just export it from the based and not have to re-define it :  _done_
- The button appears to be overflowing its container by 1 px. in some variations. : _done ; good find though 🎉_ 

#### How did you test and verify your work?
local
#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

File: packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenHeader.tsx [hunk 1]
```diff
@@ -114,13 +114,20 @@ const InterstitialScreenHeader = React.forwardRef<
       </>
     );
   };
+
+  const closeModal = () => {
+    handleClose?.('close');
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenHeader.tsx:119]: Did you accidentally pass `'close'` here?

Comment (amal-k-joy) [reply packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenHeader.tsx:119]: @matthewgallo , `handleClose` expects an argument  which is defined in   `InterstitialScreen.tsx`

**Review by makafsal — APPROVED** [review]
LGTM
