### PR TITLE
fix(DataGrid): add checkbox support

### LINKED ISSUE #5302: [Datagrids]: Add checkbox as a supported inlineEditType
### The problem

Design calls for checkbox

Screenshot 2024-05-21 at 8 41 00 AM

### The solution

Need checkbox to be supported, right now I only see text, number, selection, and date as supported options

### Design link

_No response_

### Links to other materials

_No response_

### Owner/main maintainer(s)

IBM

### Second/backup maintainer(s)

_No response_

### Product/offering

_No response_

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by AustinGitHub**
Closes #5302

Adds checkbox support 

#### What did you change?

Adds checkbox support as an optional inline edit type.

Reason I made the PR is because NextGen DataStage needs this and doesn't seem there is much movement to get this implemented. Thanks!

#### How did you test and verify your work?

Verification 

https://github.com/carbon-design-system/ibm-products/assets/10100397/ca73bd14-8769-42eb-8ae8-bfe8c5d735cf

I also validated that the data does get updated and set properly 

see it `isActive` is set to true since it as checked 

Screenshot 2024-05-30 at 5 10 56 PM

### CODE REVIEW

File: packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js [hunk 1]
```diff
@@ -485,7 +506,7 @@ export const InlineEditCell = ({
           config?.validator?.(cellValue),
       })}
     >
-      {!inEditMode && (
+      {!inEditMode && type !== 'checkbox' && (
```
Comment (AustinGitHub) [inline packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js:509]: Because on UI `checkbox` will always be visible, so no need to do any enter to edit mode here

**Comment by AustinGitHub** [comment]
Hi @kennylam and @sangeethababu9223 can you start the review process on this PR please? Thanks!

**Comment by matthewgallo** [comment]
Hey @AustinGitHub, there are some spacing issues in the cell with the checkbox, also the active cell is not able to navigate to the cells with the checkbox in it like it's able to in all of the other cells.

**Comment by AustinGitHub** [comment]
"there are some spacing issues in the cell with the checkbox"

How should the spacing be like? 

"also the active cell is not able to navigate to the cells with the checkbox in it like it's able to in all of the other cells."

It shouldn't need to. The cell for the checkbox isn't like something that needs to be double clicked to activate and go into for the checkbox. It is not hidden behind the inline edit component. Otherwise we would need to double click for checkbox to work

**Comment by matthewgallo** [comment]
The spacing should match the screenshot in https://github.com/carbon-design-system/ibm-products/issues/5302. My expectation would be that move the active cell would focus the checkbox, otherwise you lose context for the location of the active cell. I think this could probably use some design input as well.

**Comment by AustinGitHub** [comment]
Ok, I will fix the positioning

**Comment by matthewgallo** [comment]
Yes, but it visually disappears from what I am seeing. I think it could be confusing to be navigating through the datagrid and suddenly the active cell disappears when you move to a checkbox cell, giving the checkbox focus could fix this. @jjennings7 do you have any thoughts on this interaction?

**Comment by AustinGitHub** [comment]
I am not seeing this, can you provide video? Thanks!


https://github.com/carbon-design-system/ibm-products/assets/10100397/3d9c954a-e0b4-45b1-b31b-175d7d7a88ee

**Comment by AustinGitHub** [comment]
Thanks, will take a look at this use case

**Comment by AustinGitHub** [comment]
https://github.com/carbon-design-system/ibm-products/assets/10100397/62a21734-0836-4136-9543-7377524f417d

This is fixed in latest commit, let me resolve conflicts

**Comment by AustinGitHub** [comment]
It should be good now on the keyboard behavior 

https://github.com/carbon-design-system/ibm-products/assets/10100397/8006ef2c-6c71-4cfa-aa7b-9379646b9588

**Review by sangeethababu9223 — COMMENTED** [review]
@AustinGitHub ,
There seems to be some mismatch with focus behaviour in [PR preview](https://deploy-preview-5380--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-editablecell--editable-cell-usage-story&globals=viewport:basic) story and the [Production](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-editablecell--editable-cell-usage-story&globals=viewport:basic) one. 
Using `Up` / `Down` / `Right` / `Left` keys on the keyboard works as expected, but the behaviour with the `tab` key is not the same as the one in Production

**Comment by AustinGitHub** [comment]
Hi @sangeethababu9223 I see production doesn't work properly for Tab either


https://github.com/carbon-design-system/ibm-products/assets/10100397/ea20f5e6-ff3c-4358-80af-bdbeb1ca1a75

**Review by sangeethababu9223 — COMMENTED** [review]
Hi @AustinGitHub,
The focus behaviour in the production is as per w3 standards. 
Please refer [the link]( https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/ ) for details.
As per the above reference navigation inside the grid is done by `up`/`down`/`left`/`right` keys.

**Comment by sangeethababu9223** [comment]
Hi @AustinGitHub,
Please see the attached screen recordings:

Preview:

https://github.com/carbon-design-system/ibm-products/assets/58620134/2f2e694e-7ac4-44e4-b6d4-ca7cce5b9c39



Production:

https://github.com/carbon-design-system/ibm-products/assets/58620134/e7f27926-fbf1-4906-b343-0e0fc41f4636

Both preview and production works as expected while using `up`/`down`/`left`/`right` keys. The issue is while using `tab` key.

**Comment by AustinGitHub** [comment]
ok, I will check

**Comment by AustinGitHub** [comment]
So is this the expected behavior then? 

https://github.com/carbon-design-system/ibm-products/assets/10100397/78611a4d-ce79-4062-96a1-b4238854761f

**Comment by AustinGitHub** [comment]
Hi, any update on this? Thanks!

**Comment by AustinGitHub** [comment]
Conflicts are fixed

**Review by sangeethababu9223 — APPROVED** [review]
LGTM

**Comment by AustinGitHub** [comment]
Hi @matthewgallo can you help with the labels, thanks!

**Review by matthewgallo — APPROVED** [review]
