### PR TITLE
fix(coachmark): add closeIconDescription

### LINKED ISSUE #6629: [a11y]: CoachMark: closeIconDescription effectively hardcoded to English
### Package

@carbon/ibm-products

### Browser

Chrome

### Operating System

MacOS

### Package version

2.56.0

### React version

18

### Automated testing tool and ruleset

manual inspection

### Assistive technology

_No response_

### Description

`CoachmarkDragbar` has a `closeIconDescription` with a default value of 'Close':

```ts
export let CoachmarkDragbar = React.forwardRef<
  HTMLElement,
  CoachmarkDragbarProps
>(
  (
    {
      a11yKeyboardHandler,
      closeIconDescription = defaults.closeIconDescription,
...
```

However, `CoachmarkDragbar` is specifically listed as an internal component:

```js
/**
 * DO NOT USE. This component is for the exclusive use
 * of other Onboarding components.
 */
```

When `CoachmarkDragbar` is instantiated from `CoachmarkOverlay`, there's no way to set the `closeIconDescription`:

```
<CoachmarkDragbar
  a11yKeyboardHandler={handleKeyPress}
  onBlur={() => setA11yDragMode(false)}
  onDrag={handleDrag}
  theme={theme}
  onClose={onClose}
/>
```

Likewise when `CoachmarkOverlay` is created from `Coachmark` itself.

### WCAG 2.1 Violation

_No response_

### Reproduction/example

N/A

### Steps to reproduce

N/A

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #6629 

Added a closeIconDescription prop in Coachmark

#### What did you change?  

- packages/ibm-products/src/components/Coachmark/Coachmark.stories.jsx
- packages/ibm-products/src/components/Coachmark/Coachmark.tsx
- packages/ibm-products/src/components/Coachmark/CoachmarkDragbar.tsx
- packages/ibm-products/src/components/Coachmark/CoachmarkHeader.tsx
- packages/ibm-products/src/components/Coachmark/utils/context.ts

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

**Review by amal-k-joy — DISMISSED** [review]

File: packages/ibm-products/src/components/Coachmark/CoachmarkDragbar.tsx [hunk 1]
```diff
@@ -141,7 +138,7 @@ export let CoachmarkDragbar = React.forwardRef<
             kind="ghost"
             size="sm"
             renderIcon={Close}
-            iconDescription={closeIconDescription}
+            iconDescription={closeIconDescription ?? 'Close'}
```
Comment (paul-balchin-ibm) [inline packages/ibm-products/src/components/Coachmark/CoachmarkDragbar.tsx]: Would it make more sense to move `?? 'Close'` to line 105, where `closeIconDescription` is being declared?

File: packages/ibm-products/src/components/Coachmark/CoachmarkHeader.tsx [hunk 2]
```diff
@@ -83,7 +80,7 @@ export let CoachmarkHeader = React.forwardRef<
               kind="ghost"
               size="sm"
               renderIcon={Close}
-              iconDescription={closeIconDescription}
+              iconDescription={closeIconDescription ?? 'Close'}
```
Comment (paul-balchin-ibm) [inline packages/ibm-products/src/components/Coachmark/CoachmarkHeader.tsx]: Would it make more sense to move `?? 'Close'` to line 65, where `closeIconDescription` is being declared?

**Review by paul-balchin-ibm — DISMISSED** [review]

File: packages/ibm-products/src/components/Coachmark/CoachmarkDragbar.tsx (hunk 1 above)
Comment (anamikaanu96) [reply packages/ibm-products/src/components/Coachmark/CoachmarkDragbar.tsx]: I updated it to use the context value as the default value.

File: packages/ibm-products/src/components/Coachmark/Coachmark.tsx [hunk 3]
```diff
@@ -39,6 +39,7 @@ const defaults = {
   overlayKind: 'tooltip',
   theme: 'light',
   isOpenByDefault: false,
+  closeIconDescription: 'Close',
```
Comment (davidmenendez) [inline packages/ibm-products/src/components/Coachmark/Coachmark.tsx]: we should just leave this as an empty string. we should avoid adding default strings when possible.

File: packages/ibm-products/src/components/Coachmark/utils/context.ts [hunk 4]
```diff
@@ -25,6 +25,8 @@ interface CoachmarkContextType {
     y: number;
   };
   isOpen: boolean;
+  closeIconDescription?: string;
+  tacos?: string;
```
Comment (szinta) [inline packages/ibm-products/src/components/Coachmark/utils/context.ts]: Not sure what this prop does. Please remove it if it was added by mistake.

File: packages/ibm-products/src/components/Coachmark/CoachmarkTagline.tsx [hunk 5]
```diff
@@ -65,7 +65,8 @@ export let CoachmarkTagline = React.forwardRef<
     ref
   ) => {
     const coachmark = useCoachmark();
-
+    const closeIconDesc =
+      useCoachmark()?.closeIconDescription ?? closeIconDescription;
```
Comment (szinta) [inline packages/ibm-products/src/components/Coachmark/CoachmarkTagline.tsx]: I think, this should be
`const closeIconDesc = closeIconDescription ?? useCoachmark()?.closeIconDescription;`
as it gives priority to the prop provided at the component level. If the prop isn't explicitly passed, we can fall back to the value from context.

File: packages/ibm-products/src/components/Coachmark/Coachmark.stories.jsx [hunk 6]
```diff
@@ -94,7 +98,7 @@ const Template = (args) => {
   });
   const theme = getSelectedCarbonTheme();
   const content = (
-    <Coachmark {...args} theme={theme}>
+    <Coachmark closeIconDescription="Close" {...args} theme={theme}>
```
Comment (davidmenendez) [inline packages/ibm-products/src/components/Coachmark/Coachmark.stories.jsx]: if `closeIconDescription` is coming from `args` we don't need to declare it here

File: packages/ibm-products/src/components/CoachmarkFixed/CoachmarkFixed.stories.jsx [hunk 7]
```diff
@@ -47,7 +47,7 @@ export default {
 const Template = (args) => {
   const theme = getSelectedCarbonTheme();
   return (
-    <CoachmarkFixed {...args} theme={theme}>
+    <CoachmarkFixed {...args} theme={theme} closeIconDescription="Close">
```
Comment (davidmenendez) [inline packages/ibm-products/src/components/CoachmarkFixed/CoachmarkFixed.stories.jsx]: same comment regarding `closeIconDescription` and `args`

File: packages/ibm-products/src/components/Coachmark/Coachmark.tsx [hunk 8]
```diff
@@ -243,6 +249,7 @@ export let Coachmark = forwardRef<HTMLElement, CoachmarkProps>(
       align: align as PopoverAlignment,
       positionTune: positionTune,
       isOpen: isOpen,
+      closeIconDescription: closeIconDescription,
```
Comment (davidmenendez) [inline packages/ibm-products/src/components/Coachmark/Coachmark.tsx]: this can just be `closeIconDescription`

File: packages/ibm-products/src/components/CoachmarkStack/CoachmarkStack.tsx [hunk 9]
```diff
@@ -220,6 +223,7 @@ export let CoachmarkStack = React.forwardRef<
         onClick: () => handleClose(false),
       },
       isOpen: isOpen,
+      closeIconDescription: 'Close',
```
Comment (davidmenendez) [inline packages/ibm-products/src/components/CoachmarkStack/CoachmarkStack.tsx]: we shouldn't be hardcoding `close` here

**Review by davidmenendez — CHANGES_REQUESTED** [review]
just noticed a few small things

**Review by davidmenendez — DISMISSED** [review]
LGTM!

**Comment by davidmenendez** [comment]
unit tests are failing. looks like the coachmark tests just need to be updated to include `closeIconDescription` in the props

**Review by szinta — APPROVED** [review]
