### PR TITLE
fix(NotificationPanel): fix notification border when focused

### LINKED ISSUE #8660: Notification panel border (web component)
On web component, focus state border is very thin. Unable to determine exact width, but appears to be <1px, possibly due to overlapping borders from items above and below the focused item.

Image

Stroke width should be 1px all around: 

Image

### PR DESCRIPTION
**Pull request by ruchas31**
Closes #8660 , #8661 

Fix notification border when focused.

#### What did you change?

- Added listener events for focusin and focusout
- Added `display: none` to before border of each notification when focused.
- Added some tests for code coverage

#### How did you test and verify your work?
Storybook and ran tests locally

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

**Comment by ruchas31** [comment]
> I had 1 observations. I think the focus border width has to be 2px rather than 1px.

@amal-k-joy I also thought the same but both react and webcomponents story mentions "Stroke width should be 1px all around".

**Comment by ruchas31** [comment]
_Update_: Confirmed with @kiran-ravindra-ibm, focus border should be 2px. Have updated PR to reflect this.

**Comment by amal-k-joy** [comment]
> https://deploy-preview-9066--ibm-products-web-components.netlify.app

@ruchas31 
Looks good. 
But I observe this behaviour in WC
image

File: packages/ibm-products-web-components/src/components/notification-panel/notification-panel.ts [hunk 1]
```diff
@@ -261,6 +272,18 @@ class CDSNotificationPanel extends HostListenerMixin(LitElement) {
       next.classList.remove(`${blockClass}__notification--next`);
     }
   }
+  private _handleFocusIn(el: Element) {
+    const next = el.nextElementSibling;
+    if (next?.tagName.toLowerCase() === 'c4p-notification') {
```
Comment (amal-k-joy) [inline packages/ibm-products-web-components/src/components/notification-panel/notification-panel.ts]: lets not hard code `c4p`

Comment (ruchas31) [reply packages/ibm-products-web-components/src/components/notification-panel/notification-panel.ts]: Done, changed all places with `c4p` in this file to use `${prefix}` instead.
