### PR TITLE
test: add valid matcher for expect()

### LINKED ISSUE #7426: [Testing]: expect() without a matcher() never throws an error
### Package

Carbon for IBM Products

### Description

Some of our tests are throwing false positives.

### Component(s) impacted

All

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.65.0-rc.0

### Suggested Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Product/offering

Carbon for IBM Products

### CodeSandbox or Stackblitz example

None

### Steps to reproduce the issue (if applicable)

**None** of these tests will throw an error:

```
expect();
expect(false);
expect(null);
expect(undefined);
expect(0);
expect('');
```

**All** of the same tests - with matchers - will correctly throw an error:

```
expect().toBe(true);
expect(false).toBe(true);
expect(null).toBe(true);
expect(undefined).toBe(true);
expect(0).toBe(true);
expect('').toBe(true);
```

`expect()` alone never throws an error. It's the `.matcher()` that validates the result.

We have tests in our library that use `expect(something)` without a `.matcher()` that need to be found and updated. 

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #7426 , #7427

Added valid matcher for expect() in 23 test files 
Updated the test to check for the complete class name instead of a partial match using classList.contains. ( only found this in CreateFullPage.test.js)
Fixed the behaviour of CreateFullPage component, it was not working as expected when initialStep > StepLength  && initialStep<=0

#### What did you change?  
packages/ibm-products/src/components/ActionBar/ActionBarItem.test.js
packages/ibm-products/src/components/AddSelect/AddSelectBody.test.js
packages/ibm-products/src/components/AddSelect/AddSelectBreadcrumbs.test.js
packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js
packages/ibm-products/src/components/CreateFullPage/CreateFullPage.test.js
packages/ibm-products/src/components/Decorator/Decorator.test.js
packages/ibm-products/src/components/DecoratorBase/DecoratorBase.test.js
packages/ibm-products/src/components/DecoratorDualButton/DecoratorDualButton.test.js
packages/ibm-products/src/components/DecoratorLink/DecoratorLink.test.js
packages/ibm-products/src/components/DecoratorSingleButton/DecoratorSingleButton.test.js
packages/ibm-products/src/components/FilterPanel/FilterPanelAccordion/FilterPanelAccordion.test.js
packages/ibm-products/src/components/FilterPanel/FilterPanelAccordionItem/FilterPanelAccordionItem.test.js
packages/ibm-products/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.test.js
packages/ibm-products/src/components/HTTPErrors/HTTPErrors.test.js
packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.test.js
packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.test.js
packages/ibm-products/src/components/OptionsTile/OptionsTile.test.js
packages/ibm-products/src/components/SidePanel/SidePanel.test.js
packages/ibm-products/src/components/StatusIndicator/StatusIndicator.test.js
packages/ibm-products/src/components/TagOverflow/TagOverflow.test.js
packages/ibm-products/src/components/UserAvatar/UserAvatar.test.js
packages/ibm-products/src/components/UserProfileImage/UserProfileImage.test.js
packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx
packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.test.js

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

File: packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx [hunk 1]
```diff
@@ -300,12 +301,10 @@ export let CreateFullPage = React.forwardRef(
     ]);
 
     useEffect(() => {
-      if (!invalidInitialStepWarned?.current) {
-        checkForValidInitialStep();
-      }
+      checkForValidInitialStep();
 
       // eslint-disable-next-line react-hooks/exhaustive-deps
-    }, [initialStep, stepData]);
```
Comment (makafsal) [inline packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx:308]: @anamikaanu96  I'm a bit skeptical about this change. Have you manually verified that everything is working fine?

Comment (anamikaanu96) [reply packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx:308]: Noticed a minor issue with stepData.length not returning the expected value. To resolve this, moved stepLength to a global variable.

Now its working as expected.
Expected behaviour : Set current step as 1 when initialStep > StepLength && initialStep<=0
