### PR TITLE
fix(notification-panel): remove role on decorative image

### LINKED ISSUE #4940: `NotificationsPanel` a11y violations
## What will this achieve?
Remediate accessibility violations on `NotificationsPanel` component

## How will success be measured?
Pass **IBM Equal Access Accessibility Checker** scan

## Additional information
1. The scan shows `Accessible name does not match or contain the visible label text` for each notification in the panel
image (74)
2. The scan shows `Element with "img" role has no label or an empty label` for the empty state image
image (75)

### PR DESCRIPTION
**Pull request by ariellalgilmore**
Closes #4940

#### What did you change?

removed role="img" on empty since decorative to pass accessibility tests

#### How did you test and verify your work?

Ran the accessibility checker and confirmed it wasn't there anymore

### CODE REVIEW

**Review by szinta — DISMISSED** [review]
LGTM

File: packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js [hunk 1]
```diff
@@ -33,6 +33,7 @@ export const NotificationsIllustration = ({ theme, size, alt, ...rest }) => {
         `${blockClass}__illustration--${size}`,
       ])}
       role="img"
+      aria-label="Illustration of an empty notification state"
```
Comment (elycheea) [inline packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js:36]: Rather than hardcoding the `aria-label`, we can probably either reuse the `alt` in L38 or use `aria-labelledby`.

Comment (ariellalgilmore) [reply packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js]: oh that showed me we just actually needed something in the `title`, so we can use `illustrativeDescription` and it also solved the fix

**Review by elycheea — COMMENTED** [review]
Thought we would have to remove the title/alt too but seems like just removing role was enough.

Let’s just update the PR title to reflect the change.
(FYI, we removed `role="img"` since the image is decorative in this context.)

**Review by elycheea — APPROVED** [review]
