### PR TITLE
fix(DataSpreadsheet): Changed document querySelector to ref querySelector

### LINKED ISSUE #8626: DataSpreadsheet: Selecting a cell in one table also highlights the same cell in another table in ibm-products react component
### Package

Carbon for IBM Products

### Description

When we render two or more DataSpreadsheet components on the same page, clicking a cell in the second/third table also highlights the cell in the same row/column of the first table.

https://github.com/user-attachments/assets/4bb7ba71-e276-4f21-9ff3-d6bcd922d9d2

### Component(s) impacted

Dataspreadsheet  component in IBM products

Image

### Browser

_No response_

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.75.0

### Suggested Severity

None

### Product/offering

SCI UI

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-bozycdf6?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

1. Render 2–3 DataSpreadsheet instances on one page.
2. Click any cell in the second (or third) table.
3. Notice the matching cell in the first table is highlighted too.

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by amruthkg**
Closes #8626 

The bug was resulting from usage of document querySelector instead of ref's querySelector. The document querySelector always took the 1st instance of the DataSpreadSheet component for making changes - even if you are selecting cells from 2nd or 3rd instance. This was changed and a fallback was also given (existing document querySelector logic).

#### What did you change?
document querySelector was changed to ref querySelector - for selecting instance.

#### How did you test and verify your work?
I confirmed the fixes by manual testing. I created 2,3 instances of DataSpreadsheet in a story and then tested out the scenarios.

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

**Comment by amruthkg** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by AmruthKrishnaG** [comment]
recheck

**Comment by amruthkg** [comment]
> Thanks for your submission! We ask that you sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> I have read the DCO document and I hereby sign the DCO.
> 
> **Amruth Krishna Gopalakrishnan** seems not to be a GitHub user. You need a GitHub account to be able to sign the DCO. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request. Posted by the **DCO Assistant Lite bot**.

recheck

File: packages/ibm-products/src/components/DataSpreadsheet/utils/createActiveCellFn.js [hunk 1]
```diff
@@ -25,10 +25,13 @@ export const createActiveCellFn = ({
...
-    document.querySelector(
-      `[data-row-index="${coords.row}"][data-column-index="${coords.column}"]`
-    ) || document.querySelector(`.${blockClass}__body--td`); // if we can't find the point1 element (this can happen in the case where a virtualized row is not present anymore in the DOM), we get the default height/width of the first body cell we find
+  const point1Element = contextRef
+    ? contextRef?.current.querySelector(
+        `[data-row-index="${coords.row}"][data-column-index="${coords.column}"]`
+      ) || contextRef?.current.querySelector(`.${blockClass}__body--td`)
+    : document.querySelector(
+        `[data-row-index="${coords.row}"][data-column-index="${coords.column}"]`
+      ) || document.querySelector(`.${blockClass}__body--td`); // if we can't find the point1 element (this can happen in the case where a virtualized row is not present anymore in the DOM), we get the default height/width of the first body cell we find
```
Comment (amal-k-joy) [inline packages/ibm-products/src/components/DataSpreadsheet/utils/createActiveCellFn.js]: Can we use a variable to improve readability since the query is same?
Can we make this same change in other places as well.?
```
const spreadsheetSelector = contextRef?.current ?? document;
const point1Element=spreadsheetSelector.querySelector(
        `[data-row-index="${coords.row}"][data-column-index="${coords.column}"]`
      ) || contextRef?.current.querySelector(`.${blockClass}__body--td`);
```

**Review by amal-k-joy — CHANGES_REQUESTED** [review]
Thanks for contributing.
Looking good, 1 minor comment.
