### PR TITLE
fix(sidepanel): use section and heading and aside

### LINKED ISSUE #7274: [a11y]: unable to change the level of heading in SidePanel and its children headings properly
### Package

@carbon/ibm-products

### Browser

Chrome

### Operating System

Windows

### Package version

v2.63.0

### React version

v18.3.1

### Automated testing tool and ruleset

IBM Accessibility Requirements 1.3.1 Info and Relationships

### Assistive technology

_No response_

### Description

While I'm trying to make our product to meet IBM a11y requirement 1.3.1 https://www.ibm.com/able/requirements/requirements/?version=v7_3#1_3_1, I found the title of `SidePanel` is marked as `<h2>` hardcoded in https://github.com/carbon-design-system/ibm-products/blob/778347ee7a4bb1bf08b385177707ee9fc409d324/packages/ibm-products/src/components/SidePanel/SidePanel.tsx#L696-L711
so we cannot align the level of panel inside level 2 or higher content semantically and also cannot mark headings properly in children components of `SidePanel`.

It should be Carbon's `<Heading>` component instead of `<h2>` tag and wrap the entire panel with Carbon's `<Section>` to dynamically align the level including given children components inside properly.

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://codesandbox.io/p/devbox/cool-smoke-74c48y

### Steps to reproduce

1. Open the example app in Chrome
2. Click "Open side panel" button in the app preview
3. Open Chrome Dev Tools, or inspect "Incident management" title of the side panel
4. Find `SidePanel`'s heading is marked as `<h2>` even though `<SidePanel>` is set inside the section of "Third heading" `<h3>`, and headings of `<ChildrenContent />` "Subtitle" are marked as `<h4>`. In this case "Incident management" and "Subtitle"s are expected to be marked as `<h4>` and `<h5>` respectively.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by wkeese**
Closes #7274, contributes to #6314 (but just for React, not for web components).

Fix various `SidePanel` accessibility issues.

#### What did you change?

1. Use `Section` and `Heading` so that `SidePanel`'s heading level is correct when `SidePanel` is nested in a `Tearsheet` etc.  Also so that subheadings inside of the `SidePanel` get the right level.

2. Use `<aside>` rather than `<div role="complementary">`, as recommended by SonarQube, MDN, etc.

3. Fix SonarQube error that "Mutable variables should not be exported".

4. Fix SonarQube error about importing @carbon/react multiple times.

#### How did you test and verify your work?

Tested locally in Storybook.

### CODE REVIEW

**Comment by wkeese** [comment]
Note that the security error (about @babel/runtime) is unrelated to my changes.

File: packages/ibm-products/src/components/SidePanel/SidePanel.tsx [hunk 1]
```diff
@@ -896,13 +902,13 @@ export let SidePanel = React.forwardRef(
...
         {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions */}
-        <div
+        <Section
           {...getDevtoolsProps(componentName)}
           {...rest}
           id={id}
           className={mainPanelClassNames}
           ref={sidePanelRef}
-          role="complementary"
+          as="aside"
```
Comment (elycheea) [inline packages/ibm-products/src/components/SidePanel/SidePanel.tsx:911]: While `as="aside"` is a better implementation than `role="complementary"`, we likely should support the side panel as a `dialog` when using the slide-over variant.

That said, this matches our current implementation so we can open a separate issue for adding support to use the side panel as a dialog.

**Comment by wkeese** [comment]
Mend error is unrelated to this PR.

File: packages/ibm-products/src/components/SidePanel/SidePanel.tsx (hunk 1 above)
Comment (wkeese) [reply packages/ibm-products/src/components/SidePanel/SidePanel.tsx:911]: I guess that makes sense... actually I thought I saw a ticket about that yesterday but now I can't find it.

**Comment by elycheea** [comment]
FYI, Percy looks fine but looks like there’s a conflict.

**Review by elycheea — APPROVED** [review]
