### PR TITLE
fix(SidePanel): resolve focus wrap issue when first element is disabled

### LINKED ISSUE #5885: [SidePanel]: Focus wrap issue when first element disabled
### Package

Carbon for IBM Products

### Description

This issue #5819 is also exists in SidePanel

### Component(s) impacted

SidePanel

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.47.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

Products for IBM

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-side-panel-sidepanel--slide-over&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

1. Disable the first element of SidePanel
2. Try to use Tabbing to switch focus between controls

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by makafsal**
Closes #5885 

#### What did you change?
Implemented filter focusable elements `disabled` elements and `display === 'none'`

#### How did you test and verify your work?
`yarn test`
`yarn avt`
Storybook

### CODE REVIEW

File: packages/ibm-products/src/components/SidePanel/SidePanel.tsx [hunk 1]
```diff
@@ -622,17 +619,34 @@ export let SidePanel = React.forwardRef(
...
       if (open) {
         setTimeout(() => {
-          if (selectorPrimaryFocus) {
-            const primeFocusEl = document?.querySelector(selectorPrimaryFocus);
-            if (primeFocusEl) {
+          if (
+            selectorPrimaryFocus &&
+            getSpecificElement(sidePanelRef?.current, selectorPrimaryFocus)
+          ) {
+            // const primeFocusEl = document?.querySelector(selectorPrimaryFocus);
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/SidePanel/SidePanel.tsx:626]: Can you remove this line?

**Review by sangeethababu9223 — APPROVED** [review]
