### PR TITLE
fix(ConditionBuilder):  flickering sometimes while hovering on add new group/ condition/ subgroup and when there is scroll

### LINKED ISSUE #7727: Bug: conditionBuilder flickering sometimes while hovering on add new group and when there is scroll
https://github.com/user-attachments/assets/1fc09117-4543-409e-8a52-c338571520df

### PR DESCRIPTION
**Pull request by amal-k-joy**
Closes #7727

While hover on add condition or add subgroup or new group, we show the preview of the content.

#### What did you change?
    This fix addresses a flickering issue when hovering over "Add Condition" or "Add Subgroup".
     On hover, the component inserts a preview element below, ideally pushing the layout downward to create space.
     However, if the container is scrolled to the bottom, the layout may instead shift content upward,
     breaking the hover chain and causing the preview to flicker.
      Fix: When showing the preview on hover, if the scroll position is at the bottom,
     scrolling up by 1px prevents layout shift from breaking the hover chain and eliminates flickering.

#### How did you test and verify your work?
storybook

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

File: packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.tsx [hunk 1]
```diff
@@ -216,7 +216,7 @@ const ConditionBuilderContent = ({
       <div className={`${blockClass}__content-container`} {...wrapperRole}>
         {rootState &&
           rootState?.groups?.map((eachGroup, groupIndex) => (
-            <div key={eachGroup.id} className={`${blockClass}__group-wrapper`}>
+            <div key={eachGroup.id} className={`${blockClass}__group-wrapper `}>
```
Comment (makafsal) [inline packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.tsx]: Do we need a space here?

File: packages/ibm-products/src/components/ConditionBuilder/ConditionGroupBuilder/ConditionGroupBuilder.tsx [hunk 2]
```diff
@@ -65,11 +71,73 @@ const ConditionGroupBuilder = ({
     ]);
   const { statementConfig } = useDataConfigs();
   const { variant, conditionBuilderRef } = useContext(ConditionBuilderContext);
+
```
Comment (makafsal) [inline packages/ibm-products/src/components/ConditionBuilder/ConditionGroupBuilder/ConditionGroupBuilder.tsx]: Is this line necessary?

**Review by makafsal — APPROVED** [review]
LGTM
