### PR TITLE
fix(Datagrid): select all checkbox to select current page

### LINKED ISSUE #5898: DataGrid select all doesn't work as expected
### Package

Carbon for IBM Products

### Description

- Create a DataGrid component , set  batchActions: true, 
- When select all button is clicked , it selects all the button 
- Uncheck Select All, only unselects the current page data

https://github.com/user-attachments/assets/b13e32da-23d1-42ca-b15e-9070537070a8

### Component(s) impacted

DataGrid batch action

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.46.0",

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

NA

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/datagrid-tooltip-hover-issue-26hqww?file=%2Fsrc%2FExample.js%3A203%2C25

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by devadula-nandan**
Closes #5898 

this pr adds the intended behaviour to the component.

#### What did you change?
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.tsx

#### How did you test and verify your work?
storybook, checked locally combining `batch actions` and `pagination` story

### CODE REVIEW

File: packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.tsx [hunk 1]
```diff
@@ -79,12 +79,13 @@ const SelectAll = (datagridState: DataGridState) => {
...
-      getRowId,
-      isChecked: event.target.checked,
-      indeterminate,
+    // deselect all rows first
+    (getToggleAllRowsSelectedProps as any)?.()?.onChange({
+      target: { checked: false },
+    });
+    // select all row on current page
+    (getToggleAllPageRowsSelectedProps as any)().onChange({
+      target: { checked: true },
```
Comment (AlexanderMelox) [inline packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.tsx:88]: I think this might be too extensive. A better way is to only select the row if the row isn't disabled. What do you think?

Comment (devadula-nandan) [reply packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.tsx]: Hi @AlexanderMelox ,

I have noticed a few other inconsistencies, with this select-all feature
1) while we have selections on other pages, and if we click on the indeterminate state on any page, it deselects other pages as well, while the expected behavior is, that it should deselect the rows only on the current page. (will be fixed in this pr)
2) `Select all` button in the batch actions, selects the disabled rows, on other pages, maybe [this](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js#L116) action needs a refactor (will be raising a separate issue for this)

I have converted this pr to a draft, to recreate a multi-use case on the pagination story, to verify the changes, and I'll be reverting the story once its ready.

**Review by elycheea — COMMENTED** [review]
Looks good but we should probably add a test case for this so we’re less likely to see another regression. 😅

File: packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js [hunk 2]
```diff
@@ -137,6 +149,53 @@ export const stateReducer = (newState, action) => {
...
+      const newSelectedRowIds = {};
+      if (rows) {
+        const newSelectedRowData = {};
+        rows.forEach((row) => {
+          const props = row.getRowProps?.();
+          if (props && props.disabled) {
+            return;
+          }
+          if (props) {
+            if (!indeterminate && !isChecked) {
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js:166]:
```suggestion
            if (!indeterminate && isChecked) {
```

Did you mean this instead? Otherwise, the value of `datagridState?.state?.selectedRowData` is always `{}`.

Comment (devadula-nandan) [reply packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js]: right

**Review by matthewgallo — APPROVED** [review]

**Review by davidmenendez — APPROVED** [review]
