### PR TITLE
fix(ProductiveCard): make children prop optional

### LINKED ISSUE #7350: `ProductiveCard`'s `children` prop isn't optional
### Package

Carbon for IBM Products

### Description

`ProductiveCard`'s `children` prop isn't optional. I do not see anything in https://pages.github.ibm.com/carbon/ibm-products/components/card/productive-card/usage/ indicating that `children` should be required. In my usage, my card is serving as a bookmark and the card doesn't have `children`. I am getting a type error because it doesn't have `children`.

One odd thing I noticed in the code for the component is that there are two `children` props and one of them is commented out. I don't see any comments in https://github.com/carbon-design-system/ibm-products/pull/5278 indicating why that was done.

https://github.com/carbon-design-system/ibm-products/blob/d833440758acd738b511def41fb0a682e14697de/packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx#L54-L63

### Component(s) impacted

ProductiveCard

### Browser

_No response_

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.64.0

### Suggested Severity

None

### Product/offering

DataPower

### CodeSandbox or Stackblitz example

N/A

### Steps to reproduce the issue (if applicable)

1. Paste the following code into a TypeScript environment:

```tsx
const Card = (
  <ProductiveCard
    key={name}
    title={
      <TitleContainer>
        <Icon />
        <span>{title}</span>
      </TitleContainer>
    }
    onClick={() => undefined}
    onKeyDown={() => undefined}
  />
);
```
2. See type error:

type error

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by makafsal**
Closes #7350 

#### What did you change?
Made `children` a prop option in the interface

#### How did you test and verify your work?
Manual
`yarn test`

### CODE REVIEW

**Review by davidmenendez — APPROVED** [review]

File: packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx [hunk 1]
```diff
@@ -51,17 +51,10 @@ export interface ProductiveCardProps extends PropsWithChildren {
...
-   * Content that shows in the body of the card
-   */
-  // children: PropTypes.node,
   /**
    * Optional user provided class
    */
   className?: string;
-
-  children: ReactNode;
-
```
Comment (AlexanderMelox) [inline packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx:64]: Isn't this just removing it from the types? Wouldn't it be better to do this?
```
children?: ReactNode;
```

**Review by AlexanderMelox — APPROVED** [review]

File: packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx (hunk 1 above)
Comment (davidmenendez) [reply packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx:64]: Extending propswithchildren implicitly does that, no? I guess I never considered the nuances of one versus the other. If im wrong please let me know!

Comment (davidmenendez) [reply packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx:64]: based on this [article](https://blog.logrocket.com/react-children-prop-typescript/) i think either is fine to use. the [definition of PropWithChildren](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d076add9f29db350a19bd94c37b197729cc02f87/types/react/index.d.ts#L822) is literally that line
