### PR TITLE
fix(FullPageError): accessibility violations

### LINKED ISSUE #6230: [a11y]: Full Page Error, Screen Reader Incorrectly Announces "Open Menu" for Close Icon
### Package

@carbon/ibm-products

### Browser

Firefox

### Operating System

Windows

### Package version

v2.52.0-rc.0

### React version

_No response_

### Automated testing tool and ruleset

manual

### Assistive technology

JAWS

### Description

Reported by Raghu during QA Audit.

After activating the open menu, the close icon appears, but the screen reader announces it as "open menu" instead of providing the correct context for the close action.

The close icon should be announced accurately by the screen reader as "close menu" or similar, clearly indicating its function to users. This ensures that users understand that they can close the menu rather than opening it again.

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-full-page-error-fullpageerror--full-page-error&globals=viewport:basic

### Steps to reproduce

This was reported in all variants of the Full Page Error.

Open Full Page Error, Click on the hamburger menu and observe screen Reader Announcement - incorrectly announcing  "Open Menu" for Close Icon

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #6230 #6232 #6233 

Fixed the accessibility voilations

#### What did you change? packages/ibm-products/src/components/FullPageError/FullPageError.tsx
packages/ibm-products/src/components/FullPageError/assets/Error403SVG.js
packages/ibm-products/src/components/FullPageError/assets/Error404SVG.js
packages/ibm-products/src/components/FullPageError/assets/ErrorGenericSVG.js
packages/ibm-products/src/components/FullPageError/preview-components/UiShell.js

### CODE REVIEW

File: packages/ibm-products/src/components/FullPageError/FullPageError.tsx [hunk 1]
```diff
@@ -117,7 +110,9 @@ export let FullPageError = React.forwardRef<HTMLDivElement, FullPageErrorProps>(
           <Grid className={`${blockClass}__grid`}>
             <Column sm={4} md={3} lg={6} className={`${blockClass}__column`}>
               <h1 className={`${blockClass}__title`}>
-                <span className={`${blockClass}__label`}>↳ {label}</span>
+                <span className={`${blockClass}__label`} aria-hidden="true">
+                  ↳ {label}
+                </span>
```
Comment (devadula-nandan) [inline packages/ibm-products/src/components/FullPageError/FullPageError.tsx:115]: Ticket #6233 mentions that ↳ symbol is unnecessary for screen readers
But this change will also prevent screen readers from recognising the error label. Could you please revise this to ensure the error label remains accessible to screen readers?

**Review by devadula-nandan — CHANGES_REQUESTED** [review]
1 change request, rest looks good

**Review by makafsal — APPROVED** [review]
