### PR TITLE
fix: tab stop issue in coachmark patterns

### LINKED ISSUE #6965: [Coachmark]: Tab stops are not working properly
### Package

Carbon for IBM Products

### Description

| Bug                | Update                                                                                       |  
|------------------------|-----------------------------------------------------------------------------------------------|  
| **Tab stops**: Tab stop after learn more button on the first step slides the next step into view but only half way. Image      | Tab  order should be Learn more -> back button (if one is present)  -> next button

https://github.com/user-attachments/assets/2fb0a453-4d7d-48a7-b8b9-1fe3e8050502

### Component(s) impacted

Coachmark

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

Carbon for IBM Products v2.60.0

### Suggested Severity

None

### Product/offering

Carbon for IBM Products

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/experimental-onboarding-coachmark-coachmarkstack--coachmark-stack&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

Tested: [Fixed coachmark](https://ibm-products.carbondesignsystem.com/?path=/story/experimental-onboarding-coachmark-coachmarkfixed--coachmark-fixed&globals=viewport:basic) and [Stacked coachmark](https://ibm-products.carbondesignsystem.com/?path=/story/experimental-onboarding-coachmark-coachmarkstack--coachmark-stack&globals=viewport:basic)

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #6965 

Fixed the tab issue in coachmark patterns 
1) CoachmarkFixed 
2) CoachmarkStacked

#### What did you change? 
Added refs for focus control and implemented logic to manage tabIndex on carousel items.

- packages/ibm-products/src/patterns/CoachmarkFixed/example/components/CoachmarkFixedExample.tsx
- packages/ibm-products/src/patterns/CoachmarkStacked/example/components/CoachmarkStackedExample.tsx

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

File: packages/ibm-products/src/patterns/CoachmarkFixed/example/components/CoachmarkFixedExample.tsx [hunk 1]
```diff
@@ -96,24 +94,86 @@ export const CoachmarkFixedExample = (args) => {
...
+      item.setAttribute('aria-hidden', String(!isActive));
+      const focusableElements = getFocusableElements(item);
+
+      //For active item: make elements focusable (tabIndex=0)
+      //For inactive items: make elements NOT focusable (tabIndex=-1)
+      focusableElements.forEach((el) => {
+        (el as HTMLElement).tabIndex = isActive ? 0 : -1;
+      });
+    });
+  }, []);
```
Comment (szinta) [inline packages/ibm-products/src/patterns/CoachmarkFixed/example/components/CoachmarkFixedExample.tsx:128]:
```suggestion
  const updateCarouselItemsTabIndex = useCallback((activeIndex: number) => {
    carouselItemsRef.current.forEach((item, idx) => {
      const isActive = activeIndex === idx ?  true:  false;
      item.setAttribute('aria-hidden', String(!isActive));
    });
  }, []);
```

Comment (szinta) [reply packages/ibm-products/src/patterns/CoachmarkFixed/example/components/CoachmarkFixedExample.tsx:128]: will this work?

Comment (anamikaanu96) [reply packages/ibm-products/src/patterns/CoachmarkFixed/example/components/CoachmarkFixedExample.tsx:128]: Hey @szinta, thanks for the review!
Setting aria-hidden alone is insufficient. While it hides content from screen readers, it does not prevent keyboard navigation. Users can still press Tab and focus on interactive elements (buttons, links, inputs) inside hidden carousel items.

**Review by makafsal — DISMISSED** [review]

File: packages/ibm-products/src/components/Coachmark/next/Coachmark/ContentHeader.tsx [hunk 2]
```diff
@@ -53,7 +53,8 @@ export const ContentHeader = forwardRef<HTMLDivElement, ContentHeaderProps>(
     const handleRef = ref || headerRef;
     const contentHeaderBlockClass = `${blockClass}--content-header`;
 
-    const closeBubble = () => {
+    const closeBubble = (e?: React.MouseEvent) => {
+      e?.stopPropagation();
```
Comment (amal-k-joy) [inline packages/ibm-products/src/components/Coachmark/next/Coachmark/ContentHeader.tsx:57]: Do we still need to stopPropagation after popover fix?

File: packages/ibm-products/src/patterns/CoachmarkFixed/example/components/CoachmarkFixedExample.tsx [hunk 3]
```diff
@@ -96,24 +94,86 @@ export const CoachmarkFixedExample = (args) => {
...
-  }, [isOpen]);
-
   const handleTaglineClick = () => {
     setIsOpen((isOpen) => !isOpen);
   };
 
+  //get all focusable elements within a container
+  const getFocusableElements = (container: HTMLElement) => {
+    return container.querySelectorAll(
+      'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex="0"]'
```
Comment (amal-k-joy) [inline packages/ibm-products/src/patterns/CoachmarkFixed/example/components/CoachmarkFixedExample.tsx]: Instead of querying all the input elements individually, can we apply the inert attribute directly to the carousel view element itself.
refer https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products-web-components/src/components/interstitial-screen/interstitial-screen-body.ts#L145

File: packages/ibm-products/src/patterns/CoachmarkStacked/example/components/CoachmarkStackedExample.tsx [hunk 4]
```diff
@@ -230,21 +238,101 @@ export const CoachmarkStackedExample = ({ prefix = 'c4p', ...args }) => {
...
+      if (activeIndex === idx) {
+        isActive = true;
+      }
+
+      item.setAttribute('aria-hidden', String(!isActive));
+      const focusableElements = getFocusableElements(item);
+
+      //For active item: make elements focusable (tabIndex=0)
+      //For inactive items: make elements NOT focusable (tabIndex=-1)
+      focusableElements.forEach((el) => {
```
Comment (amal-k-joy) [inline packages/ibm-products/src/patterns/CoachmarkStacked/example/components/CoachmarkStackedExample.tsx]: same comment as abouve

File: packages/ibm-products/src/components/Coachmark/next/Coachmark/ContentHeader.tsx (hunk 2 above)
Comment (anamikaanu96) [reply packages/ibm-products/src/components/Coachmark/next/Coachmark/ContentHeader.tsx:57]: This is not popover, we are using bubble here.
