### PR TITLE
fix(NotificationPanel): focus return to trigger on closing notification panel

### LINKED ISSUE #6089: [Notifications Panel]: Focus return to the trigger button
### Package

Carbon for IBM Products

### Description

Focus return to the trigger button on closing the `Notification panel` should be handled in the component not in stories for better adapter experience.

### Component(s) impacted

Notifications Panel

### Browser

_No response_

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.50.0-rc.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

NA

### CodeSandbox or Stackblitz example

https://ibm-products.carbondesignsystem.com/?path=/story/overview-welcome--overview&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by sangeethababu9223**
Closes #6089 

Focus return to the trigger button on closing the Notification panel should be handled in the component not in stories for better adapter experience.

#### What did you change?
Added option to pass trigger button reference `triggerButtonref` as prop to the `Notification Panel`component and focus being returned from the component itself instead of being done in the stories.

### CODE REVIEW

File: packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx [hunk 1]
```diff
@@ -227,6 +233,11 @@ export interface NotificationsPanelProps {
    */
   todayLabel?: string;
 
+  /**
+   * Reference to trigger button
+   */
+  triggerButtonref?: RefObject<any>;
```
Comment (makafsal) [inline packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx:239]: Better change the prop name `triggerButtonref` to triggerButtonRef

Comment (sangeethababu9223) [reply packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx]: Thanks @makafsal.
Updated now!

**Review by anamikaanu96 — APPROVED** [review]
LGTM

**Review by makafsal — APPROVED** [review]
