### PR TITLE
fix(side-panel): resolve focus trap issue in side-panel web component

### LINKED ISSUE #7915: [side-panel]: Focus trap not working in the SlideOver side-panel
### Package

Carbon for IBM Products

### Description

Focus trap not working in the SlideOver side-panel:

https://github.com/user-attachments/assets/1e6f56fe-e4bc-43fe-af4e-7852e09c1815

### Component(s) impacted

side-panel web component

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v0.20.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

Carbon for IBM Products Web Components

### CodeSandbox or Stackblitz example

https://ibm-products-web-components.carbondesignsystem.com/?path=/story/components-sidepanel--slide-over

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by makafsal**
Closes #7915 

Resolve focus trap issue

#### What did you change?
Changed the current implementation

#### How did you test and verify your work?

Storybook

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

**Comment by makafsal** [comment]
> this is great! love the implementation.
> 
> i think we should work on creating a focus trap utility. we have a few different components where we're implementing focus trapping and it would be great to consolidate the functionality into a single function. that would also help to alleviate my other thought, which is testing. if we decouple this into it's own utility it'll make testing easier.
> 
> @makafsal do you know if there's been any discussion or an issue to create a focus trap utility? if not that's something we can work on and in the short term we should add some tests, but that can be done in a follow up issue / pr 👍

Yeah, I've already created one [issue](https://github.com/carbon-design-system/ibm-products/issues/7731) for utility-related tasks. I think we can have utility-related discussions over there.

Found focus-related issues in [Tearsheet](https://github.com/carbon-design-system/ibm-products/issues/7951) and [Modal (core)](https://github.com/carbon-design-system/carbon/issues/20073) web components as well.

File: packages/ibm-products-web-components/src/components/side-panel/side-panel.ts [hunk 1]
```diff
@@ -177,63 +129,75 @@ class CDSSidePanel extends HostListenerMixin(LitElement) {
...
+  protected _handleHostKeydown = (event: KeyboardEvent) => {
+    if (event.key === 'Tab' && !this.slideIn) {
+      const { first: _firstElement, last: _lastElement } = this.getFocusable();
+
+      if (
+        event.shiftKey &&
+        (this.shadowRoot?.activeElement === _firstElement ||
+          document.activeElement === _firstElement)
+      ) {
+        event.preventDefault();
```
Comment (matthewgallo) [inline packages/ibm-products-web-components/src/components/side-panel/side-panel.ts:194]: Small thing, but since you're calling `event.preventDefault()` from both inside the `if` and `else` blocks, can you just move it outside so it's just called once?

Comment (makafsal) [reply packages/ibm-products-web-components/src/components/side-panel/side-panel.ts:194]: No, only want to `preventDefault` when the condition is satisfied; otherwise, we need the default behavior.

Comment (matthewgallo) [reply packages/ibm-products-web-components/src/components/side-panel/side-panel.ts:194]: Ahh I see, one check is for first element and the other is for the last element.
