### PR TITLE
fix: update format script

### LINKED ISSUE #8106: [Bug]: Fix format scripts
a recent [PR](https://github.com/carbon-design-system/ibm-products/actions/runs/17109275649/job/48674417220?pr=8096) is breaking because the format scripts don't target the docs folder. this should be updated

### PR DESCRIPTION
**Pull request by davidmenendez**
closes #8106

### CODE REVIEW

File: scripts/example-gallery-builder/update-example/templates/src/App.jsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import React from 'react';
 import { ThemeProvider } from './ThemeSelector/ThemeContext';
 import { ThemeDropdown } from './ThemeSelector/ThemeDropdown';
-IMPORT_IBM_PRODUCTS_CONFIGimport Example from './Example/Example';
```
Comment (matthewgallo) [inline scripts/example-gallery-builder/update-example/templates/src/App.jsx]: We want to keep this ^^

**Comment by matthewgallo** [comment]
I also wonder if the reason there was formatting issues in https://github.com/carbon-design-system/ibm-products/pull/8096 was because the `precommit` hooks didn't run. I notice there is not commit prefix (`chore`, `feat`, `docs`, etc), which means the format script didn't run.

**Review by jlongshore — DISMISSED** [review]
LGTM

**Review by matthewgallo — DISMISSED** [review]

**Review by matthewgallo — DISMISSED** [review]

File: packages/ibm-products-web-components/src/patterns/saving/saving.mdx [hunk 2]
```diff
@@ -59,15 +56,22 @@ ${dirtyInput && status !== 'default'
...
   <cds-button
-    @click=${onRequestSave}
+    @click="${onRequestSave}"
     kind="primary"
-    ?disabled=${status === 'in-progress'}
+    ?disabled="${status"
+    =""
+    =""
+    ="in-progress"
+    }
```
Comment (jlongshore) [inline packages/ibm-products-web-components/src/patterns/saving/saving.mdx]: Did this get munged?

**Review by jlongshore — DISMISSED** [review]
LGTM

File: packages/ibm-products-web-components/src/components/notification-panel/notification-panel.mdx [hunk 3]
```diff
@@ -32,83 +41,72 @@ import '@carbon/ibm-products-web-components/es/components/notification-panel/ind
...
-        })}
-      `
-    : ''}
+  ${dataToday.length > 0 ? html` ${dataToday.map((item) => { return html`
+  <c4p-notification
+    slot="today"
+    .open="${args.open}"
+    @c4p-notification-click="${item.onNotificationClick}"
+    @c4p-notification-dismiss="${()"
+    =""
```
Comment (matthewgallo) [inline packages/ibm-products-web-components/src/components/notification-panel/notification-panel.mdx]: Looks like this is another one

File: packages/ibm-products-web-components/src/components/notification-panel/notification-panel.mdx [hunk 4]
```diff
@@ -32,83 +41,72 @@ import '@carbon/ibm-products-web-components/es/components/notification-panel/ind
...
+    </cds-heading>
+    <div slot="description">${item.description}</div>
+  </c4p-notification>
+  `; })} ` : ''} ${dataPrevious.length > 0 ? html` ${dataPrevious.map((item) =>
+  { return html`
+  <c4p-notification
+    slot="previous"
+    @c4p-notification-click="${item.onNotificationClick}"
+    @c4p-notification-dismiss="${()"
+    =""
```
Comment (matthewgallo) [inline packages/ibm-products-web-components/src/components/notification-panel/notification-panel.mdx]: Here too

**Review by jlongshore — APPROVED** [review]
