### PR TITLE
fix(tearsheet): Firefox focuses Tearsheet content div with scroll

### LINKED ISSUE #5745: [a11y]:  Tearsheet focus not coming on ContexSwitcher
### Package

@carbon/ibm-products

### Browser

Chrome, Firefox

### Operating System

MacOS

### Package version

v2.27

### React version

v17.0.2

### Automated testing tool and ruleset

Manual

### Assistive technology

_No response_

### Description

In the tearsheet component, I am using ContextSwitcher component . While navigation through keyboard, on pressing Shift+Tab the focus goes to the contextswitcher and the same doesnt work in case of tab key press

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet--with-navigation&globals=viewport:basic

### Steps to reproduce

Use a ContextSwitcher component 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by makafsal**
Closes #5745 

#### What did you change?
`tabIndex: -1` for `div.c4p--tearsheet__content` element

#### How did you test and verify your work?
`yarn avt`
Storybook

### CODE REVIEW

**Review by matthewgallo — APPROVED** [review]

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx [hunk 1]
```diff
@@ -550,6 +550,9 @@ export const TearsheetShell = React.forwardRef(
                     alwaysRender={
                       !!(influencer && influencerPosition === 'right')
                     }
+                    {...{
+                      tabIndex: -1,
```
Comment (davidmenendez) [inline packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:554]: instead of trying to bypass the typescript check here i think we should just include `tabIndex` in the type definition

**Review by davidmenendez — CHANGES_REQUESTED** [review]

**Review by davidmenendez — APPROVED** [review]

**Review by matthewgallo — APPROVED** [review]
