### PR TITLE
fix(CreateTearsheet): accessibility violation

### LINKED ISSUE #7562: [a11y] Fix accessibility violations in Create Tearsheet
https://github.com/carbon-design-system/ibm-products/pull/7533#issuecomment

Once the violations are resolved, remove the skip and enable the accessibility test in CreateTearsheet.

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #7562 

Resolved violations and enabled the accessibility test in CreateTearsheet.

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

**Review by davidmenendez — DISMISSED** [review]

**Review by davidmenendez — APPROVED** [review]

**Review by davidmenendez — APPROVED** [review]

File: packages/ibm-products/src/components/CreateTearsheet/CreateTearsheetStep.tsx [hunk 1]
```diff
@@ -47,6 +47,7 @@ type fieldsetLegendTextProps =
        * Otherwise, use CSS to hide/remove this label text.
        */
       fieldsetLegendText?: string;
+      fieldsetLegendId?: React.ReactNode;
```
Comment (makafsal) [inline packages/ibm-products/src/components/CreateTearsheet/CreateTearsheetStep.tsx:50]: Give a comment by describing this prop like others. It'll be helpful for future reference.

**Review by makafsal — APPROVED** [review]
