### PR TITLE
fix(useFocus): resolve focus missing in state change

### LINKED ISSUE #6946: [Tearsheet]: The focus moves to the first element when the action button's disabled property is toggled.
### Package

Carbon for IBM Products

### Description

The focus moves to the first element when the action button's disabled property is toggled.
UseCase:- We have a form with multiple fields, and the requirement is to enable the "Continue" button only after all the required fields are filled.the focus is moving away from the currently editing field once this condition is met.

### Component(s) impacted

Tearsheet

### Browser

Chrome, Safari, Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.59.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

OpenPages

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-cqjvhd-k4woiiav?file=src%2FExample%2FExample.jsx,src%2FApp.jsx,package.json

### Steps to reproduce the issue (if applicable)

1) Enter the data in fields.
2) While entering data is second field, focus is immediately moving to first field.

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by makafsal**
Closes #6946 #7019 

#### What did you change?
Moved `claimFocus` into the hook

#### How did you test and verify your work?
`yarn test`
`yarn avt`

### CODE REVIEW

**Review by davidmenendez — CHANGES_REQUESTED** [review]
looks good but code coverage dropped. can you take a look at that? thanks!

**Comment by makafsal** [comment]
> looks good but code coverage dropped. can you take a look at that? thanks!

@davidmenendez This is used for the `Createsheet` component, which is challenging to cover in the unit test (Covered in AVT).

**Review by davidmenendez — DISMISSED** [review]

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx [hunk 1]
```diff
@@ -318,29 +317,40 @@ export const TearsheetShell = React.forwardRef(
...
+        if (
+          open &&
+          depth === position &&
+          !modalRef?.current?.contains(document.activeElement)
+        ) {
+          claimFocus();
+        }
+      });
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+    }, [depth, position]);
```
Comment (jlongshore) [inline packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:346]: Missing `open` and potentially `modalRef` in the dep array... potentially `claimFocus` (see comment below)

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx [hunk 2]
```diff
@@ -318,29 +317,40 @@ export const TearsheetShell = React.forwardRef(
...
-      if (prevOpen && !open && launcherButtonRef) {
+      if (prevOpen && !open && launcherButtonRef?.current) {
         setTimeout(() => {
-          launcherButtonRef.current.focus();
+          launcherButtonRef?.current.focus();
         }, 0);
       }
-    }, [launcherButtonRef, open, prevOpen]);
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+    }, [open, prevOpen]);
```
Comment (jlongshore) [inline packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:333]: We could add `launcherButtonRef` to the dep array and remove the `eslint-disable-next-line...` rule above. No harm in adding a ref to the array when it's kind of unknown to the linter what that really is ( [reference](https://www.epicreact.dev/why-you-shouldnt-put-refs-in-a-dependency-array#custom-hooks-and-the-ref-object-itself) )

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx [hunk 3]
```diff
@@ -318,29 +317,40 @@ export const TearsheetShell = React.forwardRef(
...
+        ) {
+          claimFocus();
+        }
+      });
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+    }, [depth, position]);
+
+    useEffect(() => {
+      if (hasError && !modalRef?.current?.contains(document.activeElement)) {
+        claimFocus();
```
Comment (jlongshore) [inline packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:350]: This may go beyond the scope of this review... but should claimFocus be wrapped in a useCallback? That would allow us to add that in the dep array of these useEffects and not worry about runaway re-renders... and we could lift some of these disable next line rules.

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx [hunk 4]
```diff
@@ -318,29 +317,40 @@ export const TearsheetShell = React.forwardRef(
...
+      }
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+    }, [hasError]);
```
Comment (jlongshore) [inline packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:353]: `modalRef` in the dep array... potentially `claimFocus` (see comment below)

File: packages/ibm-products/src/global/js/hooks/useFocus.js [hunk 5]
```diff
@@ -85,40 +85,27 @@ export const useFocus = (modalRef, selectorPrimaryFocus) => {
     }
   };
 
+  const claimFocus = () => {
```
Comment (jlongshore) [inline packages/ibm-products/src/global/js/hooks/useFocus.js:88]: Should this be wrapped in a useCallback so we can add it to the dep arrays in our useCallbacks above? If we do that we could potentially lift all of the `eslint-disable-next-line react-hooks/exhaustive-deps` rules

**Review by jlongshore — COMMENTED** [review]
Just a few observations... they could be outside the scope of what this PR is intending to do also, just looking for discussion.

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx [hunk 6]
```diff
@@ -318,29 +317,40 @@ export const TearsheetShell = React.forwardRef(
...
-      firstElement,
-      modalRef,
-      modalRefValue,
-      open,
-      position,
-      selectorPrimaryFocus,
-      hasError,
-    ]);
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+    }, [open, currentStep, effectiveHasCloseIcon]);
```
[the remark this answers is not in the document]
Comment (makafsal) [reply packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:324]: 1. `currentStep` - to handle the focus when step change in `CreateTearsheet`

2. `effectiveHasCloseIcon` - Currently, we don't have a direct way to hide the close button in ComposedModal, so we're hiding it using styles, so this will cause to appear (not visibly) the close icon then become hidden (after applying style). This causes a focus issue if the focus is on the close button initially, so we've to refocus.

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx (hunk 2 above)
Comment (makafsal) [reply packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx]: 👍

**Review by jlongshore — APPROVED** [review]
LGTM
