### PR TITLE
fix(dataspreadsheet): drag drop when we have overflow

### LINKED ISSUE #5222: Data Spreadsheet: Can't drag and drop column when there is overflow on the table
### Package

Carbon for IBM Products

### Description

https://github.com/carbon-design-system/ibm-products/assets/10100397/f44bf335-ebf8-409d-be24-c1445adb62a5

### Component(s) impacted

Data spreadsheets

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.38.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

IBM

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-data-spreadsheet-dataspreadsheet--with-many-columns&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

See video attached

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by AustinGitHub**
Closes #5222

#### What did you change?

I added code logic so we can have the table auto-scroll when we are dragging left and right. While this isn't the smoothest implementation, this is better than nothing and would appreciate if we can at least have some initial implementation and then if carbon wants to adjust later that would be fine. But right now having no functional use case is going to be something customers will point out to us. Thanks!

#### How did you test and verify your work?

Storybook

https://github.com/carbon-design-system/ibm-products/assets/10100397/9c32420f-a592-4228-984b-0bc1fb458efc

### CODE REVIEW

**Review by matthewgallo — CHANGES_REQUESTED** [review]
Thanks for working on this @AustinGitHub. One thing I'm noticing is that you can endlessly scroll to the right. I think the expected behavior would be if you reach the end of the `listContainer` element to stop any scrolling.

https://github.com/carbon-design-system/ibm-products/assets/10215203/71974e12-036a-4b77-bb64-70494fe4cb70

**Comment by AustinGitHub** [comment]
Thanks! I will take a look today

**Comment by AustinGitHub** [comment]
https://github.com/carbon-design-system/ibm-products/assets/10100397/a13b0695-6d59-4fd3-82f3-05bad4c4b92f

I fixed to best I can for that issue. I see the endless scrolling not happening anymore and in some cases it doesn't scroll but in other cases I do notice it does a little but but not endless. I don't have a lot of time to do a deep dive into trying to get an absolute fix, but I think this is manageable for now.

File: packages/ibm-products/src/components/DataSpreadsheet/utils/moveColumnIndicatorLine.js [hunk 1]
```diff
@@ -30,20 +30,53 @@ export const moveColumnIndicatorLine = ({
   const selectionAreaOrigin = ref.current.querySelector(
     `[data-matcher-id="${matcherId}"]`
   );
+
+  const listContainer = ref.current.querySelector(
+    `.${blockClass}__list--container`
+  );
+
+  let scrollSpeed = 10; // Scrolling speed
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/DataSpreadsheet/utils/moveColumnIndicatorLine.js:38]: One more thing, since these variables are not re-assigned a new value can you change from `let` to `const`?

Comment (AustinGitHub) [reply packages/ibm-products/src/components/DataSpreadsheet/utils/moveColumnIndicatorLine.js:38]: Sure I can do that

**Review by matthewgallo — DISMISSED** [review]

**Review by devadula-nandan — APPROVED** [review]
🎉

File: packages/ibm-products-styles/src/components/DataSpreadsheet/_data-spreadsheet.scss [hunk 2]
```diff
@@ -267,10 +267,6 @@ $header-cell-background: $layer-accent-01;
     width: $spacing-01;
     background-color: $background-brand;
   }
-  .#{$block-class}__th--active-header,
-  .#{$block-class}__td-th--active-header.#{$block-class}__td {
-    background-color: $background-selected-hover;
-  }
```
Comment (devadula-nandan) [inline packages/ibm-products-styles/src/components/DataSpreadsheet/_data-spreadsheet.scss:273]: any reason why we remove this style? its not highlighting the cell coordinates like before.
screenshot from production
Screenshot 2024-06-18 at 11 31 56 AM

Comment (AustinGitHub) [reply packages/ibm-products-styles/src/components/DataSpreadsheet/_data-spreadsheet.scss:273]: Yes, this class is the reason this bleed-through is occurring

Screenshot 2024-06-17 at 11 17 56 PM

Comment (devadula-nandan) [reply packages/ibm-products-styles/src/components/DataSpreadsheet/_data-spreadsheet.scss:273]: adding this background to cell container might solve this issue, could you check it once?
Screenshot 2024-06-18 at 12 13 33 PM

Comment (devadula-nandan) [reply packages/ibm-products-styles/src/components/DataSpreadsheet/_data-spreadsheet.scss:273]: we can apply default background color to the parent, as in screenshot, so we can avoid compromising on this feature?

Screenshot 2024-06-18 at 12 31 06 PM

Comment (AustinGitHub) [reply packages/ibm-products-styles/src/components/DataSpreadsheet/_data-spreadsheet.scss:273]: Thanks, I will take a look later today

Comment (AustinGitHub) [reply packages/ibm-products-styles/src/components/DataSpreadsheet/_data-spreadsheet.scss]: I have fixed this, thanks!

Screenshot 2024-06-18 at 8 52 46 AM

**Review by matthewgallo — APPROVED** [review]

**Review by devadula-nandan — APPROVED** [review]
🎉
