### PR TITLE
fix(preview__PageHeader): resolve content actions responsive issue in < 1010px viewport

### LINKED ISSUE #8862: [Preview PageHeader]: The content actions appear to break at < 1010px
### Package

Carbon for IBM Products

### Description

Resizing the window to smaller than 1010px in the [focused story](https://carbon-for-ibm-products.netlify.app/iframe.html?globals=&id=preview-pageheader--default&viewMode=story) (or 1310px in the [storybook view](https://carbon-for-ibm-products.netlify.app/?path=/story/preview-pageheader--default)) results in the primary button stacking with the icon buttons:

Image

vs.

Image

### Component(s) impacted

Preview Pageheader [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/preview-pageheader--default)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.82.0 (latest)

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Carbon teams

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/preview-pageheader--default

### Steps to reproduce the issue (if applicable)

Set your window width to less than 1010px wide when viewing the story, scroll down enough to render the actions in the breadcrumb space. 

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by makafsal**
Closes #8862 

#### What did you change?

1. Used the `PageHeader.ContentPageActions` component to render `contentActions`.

2. New value in context `isInBreadcrumbBar` and update it through the nexted context.

```
PageHeader.Root (context: isInBreadcrumbBar = undefined)
├─ BreadcrumbBar (context: isInBreadcrumbBar = true) ← Overrides!
│  └─ ContentPageActions → reads true ✅
└─ Content (context: isInBreadcrumbBar = undefined)
   └─ ContentPageActions → reads undefined ✅
```

#### How did you test and verify your work?

Storybook

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

**Comment by makafsal** [comment]
Hey @RichKummer ,
I’d like clarification on the intended behavior:

1. Are the actions shown beside the page title and those displayed in the breadcrumb bar on scroll meant to be the same?
2. Can breadcrumb actions exist without page content actions?
3. Is there any scenario where both are visible simultaneously?

CC: @amal-k-joy

**Comment by RichKummer** [comment]
@makafsal 

1. Are the actions shown beside the page title and those displayed in the breadcrumb bar on scroll meant to be the same?
    1. There’s the slot for the actions in the breadcrumb bar which is separate from the actions that can appear across from the page title. Ideally, I think it should be up to the adopter what they want to appear in the collapsed header adjacent to the breadcrumb actions – not all layouts may want that in the collapsed version.
    2. Some teams *may* want to collapsed a set of buttons next to the Page header title, some may want to have those buttons displayed in the breadcrumb bar (and do so without the breadcrumb actions). 
    3. Is there a way we can make this flexible and less opinionated? I.e. adopter has control on whether or not the actions across from the Page header appear in the collapsed header, and if they want something else entirely taking up the slot in the collapsed header.
  
2. Can breadcrumb actions exist without page content actions?
    1. I’m assuming you mean “breadcrumb action” as any of the buttons across from the breadcrumbs that appear in the same bar. They should be able to exist without page content actions if the adopter wants that configuration.
3. Is there any scenario where both are visible simultaneously?
    1. I think there are scenarios where an adopter may want both the breadcrumb actions and the header actions visible in the collapsed breadcrumb bar.

File: packages/ibm-products/src/components/PageHeader/next/context.ts [hunk 1]
```diff
@@ -27,6 +28,8 @@ type PageHeaderContextType = {
   fullyCollapsed?: boolean;
   titleClipped?: boolean;
   contentActionsClipped?: boolean;
+  breadcrumbActionsClipped?: boolean;
+  isInBreadcrumbBar?: boolean;
```
Comment (amal-k-joy) [inline packages/ibm-products/src/components/PageHeader/next/context.ts]: siince we are setting this to global context, lets make the name more specific
`isContentActionsInBreadcrumbBar`

**Comment by amal-k-joy** [comment]
> 1. I think there are scenarios where an adopter may want both the breadcrumb actions and the header actions visible in the collapsed breadcrumb bar.

Hi Afsal,

As discussed, let’s not automatically hide contentActions on breadcrumb collapse. Instead, we can expose three callbacks to the user that will be triggered in specific scenarios. This way, the user can decide whether to hide or show the actions based on their needs.

Lets create a new ticket to make these changes.
Please not we need the same changes to be done for webcomponents too. We may need to dispatch custom events there.

```
 <PageHeader.Content 
  title={title}
  onPageActionsClipped={({ isClipped }) => {

  }}
  onFullCollapsed={({ isCollapsed }) => {

  }}
  onTitleClipped={({ isClipped }) => {

  }}
/>
```


Thanks @RichKummer for the clarifications.
I think we can merge this PR now, since this will fix the broken contentActions in mobile screens.

**Review by amal-k-joy — APPROVED** [review]
