### PR TITLE
fix(build): update story imports in docs and fix circular deps

### LINKED ISSUE #7889: Fix circular dependencies surfaced in build
We have a few circular dependencies that are surfaced in our builds. These will need to be addressed to prevent any potential issues in the future.

Here is a [link](https://github.com/carbon-design-system/ibm-products/actions/runs/16473976569/job/46570417203?pr=7887#step:6:61) for reference.

### LINKED ISSUE #7890: Resolve storybook warnings surfaced in builds
We have a handful of storybook warnings during our storybook builds. These look to be primarily come from stories imported from a story doc file that don't exist, for example see [here](https://github.com/carbon-design-system/ibm-products/actions/runs/16472425023/job/46564839002?pr=7881#step:6:174).

### PR DESCRIPTION
**Pull request by matthewgallo**
Closes #7890 
Closes #7889 

Fixes storybook warnings being emitted from our builds. These are related to storybook doc files importing stories that don't exist. I also removed an old import script that is outdated and causing errors in build as well. Also, fixed the circular dependency issues and a lottie warning.

image

One last thing to clean up related to the build logs, is the inability to set a custom `$font-path` when using `@carbon/ibm-products/css/index-full-carbon.s|css` which causes all of the plex warnings in the build logs. But I'll open a separate issue.

#### What did you change?
- Welcome story, lottie warning
- Interstitial, filter panel, empty state circular deps
- Handful of story import issues
#### How did you test and verify your work?
Build logs from this PR should no longer have any storybook import warnings, circular dependencies, or lottie-web warnings
#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

File: packages/ibm-products/src/components/InterstitialScreen/context.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+/**
+ * Copyright IBM Corp. 2025, 2025
+ *
+ * This source code is licensed under the Apache-2.0 license found in the
+ * LICENSE file in the root directory of this source tree.
+ */
+
+import { createContext } from 'react';
+import { InterstitialScreenContextType } from './InterstitialScreen';
```
Comment (szinta) [inline packages/ibm-products/src/components/InterstitialScreen/context.ts]: Can we move `InterstitialScreenContextType` declaration to context file. Looks like, this line creates a circular dependency?

File: packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenFooter.tsx [hunk 2]
```diff
@@ -8,12 +8,8 @@ import React, { useContext, useEffect, useMemo, useRef, useState } from 'react';
 
 import PropTypes from 'prop-types';
 
-import {
-  ActionType,
-  blockClass,
-  disableButtonConfigType,
-  InterstitialScreenContext,
-} from './InterstitialScreen';
+import { ActionType, disableButtonConfigType } from './InterstitialScreen';
```
Comment (szinta) [inline packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenFooter.tsx]: Can we move these two to context as well so that we can avoid the import of InterstitialScreen ?

File: packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenBody.tsx [hunk 3]
```diff
@@ -14,11 +14,8 @@ import React, {
 } from 'react';
 import PropTypes from 'prop-types';
 
-import {
-  blockClass,
-  disableButtonConfigType,
-  InterstitialScreenContext,
-} from './InterstitialScreen';
+import { disableButtonConfigType } from './InterstitialScreen';
```
Comment (szinta) [inline packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenBody.tsx]: Can we move this to context so that we can avoid import of InterstitialScreen ?

**Review by szinta — CHANGES_REQUESTED** [review]
LGTM, except the circular dependency in InterstitialScreen component. I am not sure why It's not appearing in the CI build checks logs,  but I think it would be better to fix that as well to avoid any issues later.

**Review by szinta — APPROVED** [review]
