### PR TITLE
fix(Datagrid): onRowClick results in toggleRow.toggleRowSelected is not a function error in console

### LINKED ISSUE #6547: [Bug]: Carbon for IBM Products: Datagrid - onRowClick results in toggleRow.toggleRowSelected is not a function error in console
### Package

Carbon for IBM Products

### Description

Because of the fix/workaround offered for the issue (Filtering and Search in Datagrid with nested rows is not working as expected #4652
), another issue has surfaced. Using both useOnRowClick and useNestedRows with the workaround provided for https://github.com/carbon-design-system/ibm-products/issues/4652
 results in an error in the console for row clicks.

As shown in the video attached, the row click works properly on the first page, however when I move on to the second page and do the row click, an error is thrown in the console. After receiving the error, if I return to the previous page, the older selection remains but the new selection is gone.

### Component(s) impacted

**stackblitz**
https://stackblitz.com/edit/github-uzudxy-md54df?file=src%2FApp.jsx,src%2FExample%2FExample.jsx,src%2FExample%2FDatagridPagination.jsx

**Screenshot**
Image

**Video**
[Screen Recording 2024-12-05 at 4.00.23 PM.zip](https://github.com/user-attachments/files/18021670/Screen.Recording.2024-12-05.at.4.00.23.PM.zip)

### Browser

Firefox, Chrome, Safari

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "^2.50.0"

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

IBM Financial Transaction Manager(FTM)

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-uzudxy-md54df?file=src%2FApp.jsx,src%2FExample%2FExample.jsx,src%2FExample%2FDatagridPagination.jsx

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by amal-k-joy**
Closes #6547 

Added a null check for `toggleRowSelected` callback since for some rows objects, `toggleRowSelected` is not present.

#### How did you test and verify your work?
local

### CODE REVIEW

File: packages/ibm-products/src/components/Datagrid/useOnRowClick.ts [hunk 1]
```diff
@@ -35,8 +35,10 @@ const useOnRowClick = (hooks: Hooks) => {
 
           if (!withSelectRows) {
             instance.selectedFlatRows &&
-              instance.selectedFlatRows.map((toggleRow) =>
-                toggleRow.toggleRowSelected(false)
+              instance.selectedFlatRows.map(
+                (toggleRow) =>
+                  toggleRow.toggleRowSelected &&
+                  toggleRow.toggleRowSelected(false)
```
Comment (AlexanderMelox) [inline packages/ibm-products/src/components/Datagrid/useOnRowClick.ts:41]:
```suggestion
              instance.selectedFlatRows.map(
                (toggleRow) =>
                  toggleRow.toggleRowSelected?.(false)
```

Comment (AlexanderMelox) [reply packages/ibm-products/src/components/Datagrid/useOnRowClick.ts:41]: We can make it more concise with an optional chaining operator

**Review by AlexanderMelox — CHANGES_REQUESTED** [review]
Looks good just one small suggestion

**Review by anamikaanu96 — APPROVED** [review]

**Review by AlexanderMelox — APPROVED** [review]
