### PR TITLE
fix(APIKeyModal): implement useFocus hook

### LINKED ISSUE #6245: [a11y]: API Key Modal, While Modal active , parent page controls are navigable /readable:
### Package

@carbon/ibm-products

### Browser

Firefox

### Operating System

Windows

### Package version

v2.52.0-rc.0

### React version

_No response_

### Automated testing tool and ruleset

Manual testing

### Assistive technology

JAWS

### Description

Reported by Raghu during QA Audit.

Once the Generative API Modal is active , focus not Trapped with in the Modal, Keyboard navigation moving out and reading from parent page.

Expected behaviour : Once the Generative API Modal is active , focus expected to be Trapped with in the Modal, Keyboard navigation  should not move out  and  Read from parent page.

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-generating-an-api-key-apikeymodal--generate&globals=viewport:basic

### Steps to reproduce

This was reported in API Key Modal - Instant Generate.
  

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by makafsal**
Closes #6245 #6252 #6249 #6247 #6375 

#### What did you change?
Implemented the `useFocus` hook into the `APIKeyModal` component

#### How did you test and verify your work?
`yarn test`
`yarn avt`
Storybook

### CODE REVIEW

File: packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx [hunk 1]
```diff
@@ -108,13 +116,24 @@ export let APIKeyModal: React.FC<APIKeyModalProps> = forwardRef(
       ref: copyRef,
     };
     const blockClass = `${pkg.prefix}--apikey-modal`;
+    const localRef = useRef(undefined);
+    const modalRef = (ref || localRef) as MutableRefObject<HTMLDivElement>;
+    const { firstElement, keyDownListener } = useFocus(modalRef);
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx:121]: Since this is a wrapper around the Carbon modal, we also need to support `selectorPrimaryFocus`, the same way we have done in `TearsheetShell.tsx`.

**Review by anamikaanu96 — DISMISSED** [review]
Looks good!

**Review by matthewgallo — CHANGES_REQUESTED** [review]
Can you add some unit tests for the new focus updates? I'm guessing they could be fairly similar to the tests you added to tearsheet when the new focus hook was added there.

File: packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx [hunk 2]
```diff
@@ -109,13 +119,46 @@ export let APIKeyModal: React.FC<APIKeyModalProps> = forwardRef(
...
+      selectorPrimaryFocus
+    );
 
     useEffect(() => {
       if (copyRef.current && open && apiKeyLoaded) {
         copyRef.current.focus();
       }
     }, [open, apiKeyLoaded]);
 
+    useEffect(() => {
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx:135]: Since we now have a very similar `useEffect` here and in `TearsheetShell`, we should think about putting this inside a custom hook that is used in both components. I don't want to hold up this PR longer, so lets look at that after we get this merged.

**Review by matthewgallo — APPROVED** [review]

File: packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx (hunk 2 above)
Comment (makafsal) [reply packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx:135]: @matthewgallo Sounds good, may be I can create a refactor ticket for that and raise PR.
