### PR TITLE
fix(editinplace): add placeholder for text field

### LINKED ISSUE #5777: EditInPlace missing placeholder field
### Package

Carbon for IBM Products

### Description

The `EditInPlace` component does not have a placeholder field.

`EditInPlace` is similar to base carbon's TextInput and other input fields that support placeholder fields, but it's missing here.
And back in carbon v10, when it was `InlineEdit`, it had placeholder field as well.. but after upgrading to carbon v11 and renamed to `EditInPlace`, now placeholder is missing

### Component(s) impacted

I'm using the `EditInPlace` component in a Table, to follow the Data Table extensions -> Inline Editing designs described here: https://pages.github.ibm.com/cdai-design/pal/components/data-table/inline-editing/usage .. 
And when it's placed in a table and when the value is not set yet, it just appears very empty.. User cannot tell there is a field or anything there..
Screenshot 2024-07-31 at 12 53 07 PM

Not until you hover over the field, then you realize there's an edit icon appearing.. in this screenshot, my cursor is hovering over the `EditInPlace` field
Screenshot 2024-07-31 at 12 54 17 PM

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM Cloud Data Replication

### CodeSandbox or Stackblitz example

n/a

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by sangeethababu9223**
Closes #5777

Missing placeholder for the text field

#### What did you change?
added `placeholder` as prop to the component

#### How did you test and verify your work?
Storybook

### CODE REVIEW

File: packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx [hunk 1]
```diff
@@ -443,6 +449,11 @@ EditInPlace.propTypes = {
    * handler that is called when the save button is pressed or when the user removes focus from the input if it has a new value
    */
   onSave: PropTypes.func.isRequired,
+  /**
+   * Placeholder for text input
+   */
+  /**@ts-ignore*/
```
Comment (devadula-nandan) [inline packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx:455]:
```suggestion
```
as we make the prop optional in the interface, this can be removed, which shouldn't throw any error now.

File: packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx [hunk 2]
```diff
@@ -129,6 +129,10 @@ interface EditInplaceProps extends PropsWithChildren {
    * current value of the input
    */
   value: string;
+  /**
+   * placeholder for the input
+   */
+  placeholder: string;
```
Comment (devadula-nandan) [inline packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx:135]:
```suggestion
  placeholder?: string;
```
this is optional

**Review by devadula-nandan — CHANGES_REQUESTED** [review]
few changes, rest looks good.

File: packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx (hunk 2 above)
Comment (sangeethababu9223) [reply packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx]: Thanks @devadula-nandan.
The changes are updated.

**Review by matthewgallo — APPROVED** [review]

**Review by devadula-nandan — APPROVED** [review]
