### PR TITLE
fix(PageHeader): page actions without title (collapseTitle=true)

### LINKED ISSUE #7277: [PageHeader]: pageActions not visible with collapseTitle
### Package

Carbon for IBM Products

### Description

Earlier (in v1), we could show `pageActions` with `collapseTitle=true`, in v2, they're not visible.

Also, this is an unrelated secondary issue, we can't show `pageActions` with collapseTitle=true unless we also provide `actionBarItems` which I think shouldn't be required if you just need to show pageActions.

Root cause:
Image

Potential fix:
Image

### Component(s) impacted

PageHeader

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.63.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

IBM Verify

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/c11-ts-template-keajhy3m?file=src%2FApp.tsx

### Steps to reproduce the issue (if applicable)

Image

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by makafsal**
Closes #7277 #7298 

#### What did you change?
Changed styles

#### How did you test and verify your work?
`yarn test`
Storybook

### CODE REVIEW

**Review by amal-k-joy — APPROVED** [review]
LGTM

File: packages/ibm-products/src/components/PageHeader/PageHeader.tsx [hunk 1]
```diff
@@ -1035,7 +1038,7 @@ export let PageHeader = React.forwardRef(
                             />
                           </>
                         ) : (
-                          widthIsNarrow &&
+                          (widthIsNarrow || pageActions) &&
```
Comment (s100) [inline packages/ibm-products/src/components/PageHeader/PageHeader.tsx:1041]: @ntkibm This change seems to result in a strange scenario where `thePageActions(...)` renders twice in our case, once in the breadcrumb row (invisibly??) and once more in the title row. This has caused some of our tests to break because they assume that the page actions will only appear in the DOM once. I'm not sure whether to raise a bug for this, it's possible that we are misusing the component. Can you explain in more detail what this change does please?

Comment (ntkibm) [reply packages/ibm-products/src/components/PageHeader/PageHeader.tsx:1041]: hey @s100, you probably want to check with @makafsal who is the author of this pr.. i'm the reporter of the issue.. i don't have much idea about the internal code.
