### PR TITLE
fix(datagrid): tooltip missing in Customize Columns modal

### LINKED ISSUE #5909: [BUG] Tooltip not working on the Datagrid's "Customize columns" modal
### Package

Carbon for IBM Products

### Description

Tooltip with the reminder of truncated text does not show in the Datagrid's "Customize columns". I would expect a tooltip with the sentence reminder to be displayed when hovered over "the...", since the current behaviour affects accessibility.

Screenshot 2024-08-21 at 10 01 57

https://github.com/user-attachments/assets/bc20279e-b69a-458c-8a2b-6ce5afae62fb

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM's Financial Transaction Manager

### CodeSandbox or Stackblitz example

There are several examples in your Storybook: https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-datagrid-columncustomization--docs

### Steps to reproduce the issue (if applicable)

1. Pick any example with column cusomization in your story book: https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-datagrid-columncustomization--docs

2. Click on the "Customize columns" icon

3. Hover over. the truncated text in the description ("the...")

4. Observe nothing happening, where the expected behaviour would be to display a tooltip with the sentence reminder

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by sangeethababu9223**
Closes #5909

Text over flow tooltip not showing in Datagrid's `Customize Column` Tearsheet description.
Issue is with Tearsheet shell itself.

#### What did you change?

Since description is not an interactive element, instead of adding `Carbon tooltip`, `title` attribute added to the `Tearsheet Shell`. 
Used `Side Panel` text overflow as reference.

#### How did you test and verify your work?
Storybook

### CODE REVIEW

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx [hunk 1]
```diff
@@ -270,6 +272,13 @@ export const TearsheetShell = React.forwardRef(
     );
     const modalRefValue = modalRef.current;
 
+    // Function to strip html tags out of a string.
+    const stripTags = useCallback(
```
Comment (AlexanderMelox) [inline packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:276]: We wont need useCallback in React 18 so no need to add this for now

Comment (AlexanderMelox) [reply packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:276]: Will just add more cleanup later on

**Review by AlexanderMelox — APPROVED** [review]

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx (hunk 1 above)
Comment (sangeethababu9223) [reply packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:276]: Thank you!

**Review by makafsal — APPROVED** [review]
