### PR TITLE
fix(ExportModal): update status message

### LINKED ISSUE #6020: [a11y]: Export Modal, Exporting file status message not conveyed completely by the Screen reader
### Package

@carbon/ibm-products

### Browser

Firefox

### Operating System

Windows

### Package version

v2.49.0-rc.0

### React version

_No response_

### Automated testing tool and ruleset

manual

### Assistive technology

JAWS

### Description

Reported by Raghu during QA Audit.

The "Exporting file" status is not conveyed to the screen reader user, instead, it announces as "Loading", also once the process is done, the screen reader does not announce the success status visually populated as "The file has been exported.".

### Recommended fix
Any dynamic status indication must be presented to screen reader users instantly, or else the same group may not come to know about such status info. usage of aria-live was recommended on the call.

### WCAG 2.1 Violation

4.1.3 Status Messages

### Reproduction/example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-export-exportmodal--standard&globals=viewport:basic

### Steps to reproduce

open the export modal and click on export button
observe the live status is not conveyed to the user

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #6020 

Status message has been updated to convey communication effectively to screen reader users.

### CODE REVIEW

File: packages/ibm-products/src/components/ExportModal/ExportModal.tsx [hunk 1]
```diff
@@ -309,8 +309,12 @@ export let ExportModal = forwardRef(
           <div className={`${blockClass}__messaging`}>
```
Comment (sangeethababu9223) [inline packages/ibm-products/src/components/ExportModal/ExportModal.tsx:309]: @anamikaanu96 ,
Would it be better if we give `aria-live="assertive"` to this div instead of each `P` tag items?

**Review by sangeethababu9223 — APPROVED** [review]

**Review by makafsal — APPROVED** [review]
LGTM

**Review by sangeethababu9223 — APPROVED** [review]
