### PR TITLE
fix(PageHeader): ensures expected positioning even if content component is excluded

### LINKED ISSUE #7941: PageHeader (react): incorrect offsets when no content element
React counterpart to https://github.com/carbon-design-system/ibm-products/issues/7932

### PR DESCRIPTION
**Pull request by matthewgallo**
Closes #7941 

#### What did you change?
```
_page-header.scss
PageHeader.stories.js
PageHeader.tsx
```
#### How did you test and verify your work?
Storybook, did not yet include a story for this. I manually commented out the content component in the tabs story. 
#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

File: packages/ibm-products/src/components/PageHeader/next/overflowHandler.ts [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+  }
+  const originalDisplay = el.style.display;
+  if (!el.offsetParent && getComputedStyle(el).display === 'none') {
+    el.style.display = 'inline-block';
+  }
+  let size = el.getBoundingClientRect()[dimension];
+  el.style.display = originalDisplay;
+  const computedStyles = getComputedStyle(el);
+  size =
+    dimension === 'width'
```
Comment (amal-k-joy) [inline packages/ibm-products/src/components/PageHeader/next/overflowHandler.ts:34]: @matthewgallo ,
I was  just wondering, if `el` has `box-sizing : border-box` enabled, `padding` may already be included in `size`, but not sure it applies here

Comment (matthewgallo) [reply packages/ibm-products/src/components/PageHeader/next/overflowHandler.ts:34]: Good point, since `getBoundingClientRect()` always includes the padding, this can be refactored to only account for the margins

Comment (matthewgallo) [reply packages/ibm-products/src/components/PageHeader/next/overflowHandler.ts:34]: @amal-k-joy, I've updated this now to only add margins to the calculated `size`
