### PR TITLE
fix(TagSet): fix string formatting

### LINKED ISSUE #5854: [TagSet]: overflow tag tooltip shows an additional comma (,)
### Package

Carbon for IBM Products

### Description

When we hover over tagset count tag, it shows a tooltip which has an additional comma (,)

[https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-tag-set-tagset--many-tags&globals=viewport:basic](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-tag-set-tagset--many-tags&globals=viewport:basic)

tagset-comma

### Component(s) impacted

Tag set

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

V2.34.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

Infrastructure

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/interesting-aj-rxj593

### Steps to reproduce the issue (if applicable)

1. Add TagSet
2. Add more object in tags array such that rest will be shown in tags with count
3. Hover over the count tags

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by devadula-nandan**
Closes #5854 

fixes string format for the child of the `<Tag>` component, which fixes the title attribute.

#### What did you change?
packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx

#### How did you test and verify your work?
storybook

### CODE REVIEW

File: packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx [hunk 1]
```diff
@@ -147,7 +147,7 @@ export const TagSetOverflow = React.forwardRef(
             onClick={() => setPopoverOpen?.(!popoverOpen)}
             className={cx(`${blockClass}__popover-trigger`)}
           >
-            +{overflowTags.length}
+            {'+' + overflowTags.length}
```
Comment (davidmenendez) [inline packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx:150]: would prefer to just use template strings here
```
{`+${overflowTags.length}`}
```

**Review by davidmenendez — CHANGES_REQUESTED** [review]

**Review by davidmenendez — APPROVED** [review]

**Review by sangeethababu9223 — APPROVED** [review]
LGTM!
