### PR TITLE
fix(tearsheet): focus without sentinels

### LINKED ISSUE #5737: [a11y]: Screen reader identifies hidden controls in Tearsheet
### Package

@carbon/ibm-products

### Browser

Firefox

### Operating System

Windows

### Package version

v2.44.0-rc.1

### React version

_No response_

### Automated testing tool and ruleset

manual

### Assistive technology

JAWS

### Description

Reported by Raghu during screen reader testing.

Screen reader identifies “a  focus sentinel button" on both top and bottom of the modal which is not visible

1. On Arrow key navigation this Element identified both on top as well as bottom part of the modal.
2. In the page top, this control received Tab focus.
3. “Focus sentinel” button is not keyboard operable.
4. Existing label of this control is not descriptive enough to understand the purpose of this Element.

### Recommended fix
Please confirm the functional purpose of this “focus sentinel button”:
1. If there is a functional objective, make this element visually available and operable by keyboard/mouse. Provide a descriptive label to explain its purpose.
2. If not, remove tab focus and hide it from screen reader detection on both <kbd>Tab</kbd> and <kbd>Arrow</kbd> key navigation.

REF# https://github.com/carbon-design-system/carbon/issues/14203

### WCAG 2.1 Violation

1.3.1. Info & Relationships

### Reproduction/example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet--tearsheet&globals=viewport:basic

### Steps to reproduce

This was reported in all variants of the tearsheet.

Navigate tearsheet using either (or both) <kbd>Arrow</kbd> or <kbd>Tab</kbd> keys.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by makafsal**
Closes #5737 

#### What did you change?
Wrap `ComposedModal` tag with `<FeatureFlags
          flags={{
            'enable-experimental-focus-wrap-without-sentinels': true,
          }}
        >`

#### How did you test and verify your work?
Storybook

### CODE REVIEW

File: packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx [hunk 1]
```diff
@@ -33,6 +33,8 @@ import {
   ModalHeader,
   usePrefix,
   type ButtonProps,
+  /**@ts-ignore*/
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:36]: I _think_ updating our custom typings declaration file with `unstable_FeatureFlags` will remove the ts error when importing this

Comment (matthewgallo) [reply packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx:36]: https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/custom-typings/index.d.ts

**Review by davidmenendez — APPROVED** [review]
