### PR TITLE
fix(Emptystate): accessibility violation

### LINKED ISSUE #6352: [a11y]: Empty state accessibility violations
### Package

@carbon/ibm-products

### Browser

Firefox

### Operating System

Windows

### Package version

v2.53.0-rc.0

### React version

_No response_

### Automated testing tool and ruleset

Manual testing

### Assistive technology

JAWS

### Description

- [x] Heading level hierarchy is not maintained 

   Issue : Heading level hierarchy is not maintained 
   Recommended Fix : Hope  the "Empty State content block could be a  sub part of a  Main Header , as well as sub part of the Parent page : 
   Hence , expected to assign the Heading  Level  in accordance  to the  Parent page  Heading level structure .
   Generic recommendation  for maintaining the Heading level hierarchy  : Well organised headings helps the user to quickly skim through the 
   page content and get an overview. Headings should be concise and reflect the content. It is a good practice to arrange headings in an 
   hierarchical order.
   This issue is reported in all Variants of Empty State.

- [x]  Text alternative for the given Image is not meeting the WCAG Requirements

   Issue : Text alternative  for the given Image is not meeting the WCAG Requirements 
                The existing Image - "Search Lense " given with -"Test alt text":
      This Graphic not conveying any info - this  observed as "Decorative " Image -  Decorative Images expected to hide from screen reader 
      detection , which is not done .

   Recommended Fix : Please confirm  the given Image is a  Informative /Decorative , and expected to choose the fix accordingly :
       1. informative graphics should be given a descriptive alternative text so that the users of assistive technology can understand them.
       2. decorative/non informative graphics should be hidden from assistive technology so that they do not distract the user.
   This issue is reported in Empty State - with custom illustration

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-patterns-empty-state-emptystate--default&globals=viewport:basic

### Steps to reproduce

Heading level hierarchy Issue is reported in all the variants of Empty State.
Text alternative  for the given Image is not meeting the WCAG Requirements - reported in Empty State - with custom illustration

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #6352 

Solutions for empty state accessibility violations
solution for issue 1 : Heading is now composable , introduced a new prop called `headingAs` for setting the value of `as`.
solution issue 2 : since the images are decorative, they have been hidden from assistive technology.

I had a discussion with Amal today regarding the conversation in the engineering huddle. We concluded that more appropriate solution will be using `as` prop rather than using `<Heading>` without deprecating size prop.

### CODE REVIEW

File: packages/ibm-products/src/components/EmptyStates/EmptyState.tsx [hunk 1]
```diff
@@ -116,6 +121,7 @@ export let EmptyState = React.forwardRef<HTMLDivElement, EmptyStateProps>(
       illustrationPosition = defaults.position,
       link,
       size = defaults.size,
+      headingAs,
```
Comment (amal-k-joy) [inline packages/ibm-products/src/components/EmptyStates/EmptyState.tsx:124]: We can give a default value for `headingAs ` as 'h3', since currently we have this as h3

**Review by amal-k-joy — CHANGES_REQUESTED** [review]

**Review by amal-k-joy — APPROVED** [review]
LGTM

**Review by davidmenendez — APPROVED** [review]
