### PR TITLE
fix(dataGrid): focus loss on radio select

### LINKED ISSUE #5683: [a11y]: Datagrid, radio select: selection of radio buttons causes focus jump
### Package

@carbon/ibm-products

### Browser

Firefox

### Operating System

_No response_

### Package version

v2.44.0-rc.1

### React version

_No response_

### Automated testing tool and ruleset

manual

### Assistive technology

JAWS

### Description

Observation on row selection radio buttons selection:
- Selecting a radio button within the table row jumps focus to the top and announces:
"storybook-preview-frame frame"
- Screen reader doesn’t announce the radio button selection status immediately 

**Note**
Screen reader users experience difficulty navigating the table and confirming their selections.

**Recommended fix**
Ensure the selection status of the radio button elements is conveyed instantly, also avoid the focus jump caused by selection.

**User impact**
When the state of an element is not conveyed appropriately, it prevents screen reader users to interact smoothly with the page element.

### WCAG 2.1 Violation

4.1.2. Name Role Value

### Reproduction/example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid--radio-select&globals=viewport:basic

### Steps to reproduce

To reproduce this defect:

1. Use a screen reader on the row selection story.
2. Try navigating through radio buttons.
3. Try selecting a radio button.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by devadula-nandan**
Closes #5683 

returns the radio select focus, if it's lost.

#### What did you change?
packages/ibm-products/src/components/Datagrid/useSelectRows.tsx

#### How did you test and verify your work?
storybook, screen reader for mac, jaws for win 11

### CODE REVIEW

File: packages/ibm-products/src/components/Datagrid/useSelectRows.tsx [hunk 1]
```diff
@@ -119,6 +119,10 @@ const SelectRow = (datagridState) => {
       getRowId,
       selectAll: null,
     });
+    // focus the radio / checkbox if lost
+    const activeElement = document.activeElement?.id ?? '';
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/Datagrid/useSelectRows.tsx:123]: Gotta be careful to watch out for SSR apps where document will be `undefined`. You could add an optional chain here or save the active element in a ref from `useIsomorphicEffect`.

**Review by matthewgallo — CHANGES_REQUESTED** [review]

**Review by amal-k-joy — APPROVED** [review]
LGTM

**Review by matthewgallo — APPROVED** [review]
