### PR TITLE
fix(dataspreadsheet): Change condition check (fix regression)

### LINKED ISSUE #5526: [dataspreadsheet]: condition check is returning out boolean instead of render object
### Package

Carbon for IBM Products

### Description

Condition is doing this from what I am seeing, it is changing the value to false instead of keeping the object

https://github.com/carbon-design-system/ibm-products/assets/10100397/50f6c7e5-099f-47f1-9a23-59b3e6914046

The issue it is causing, the editing values are returning undefined due to the above condition. 
Note: The `(Null)` is custom code on our end, ignore that

https://github.com/carbon-design-system/ibm-products/assets/10100397/8571ba18-9c11-41d3-9451-51aab0fe4123

### Component(s) impacted

Dataspreadsheets

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.40

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

IBM

### CodeSandbox or Stackblitz example

N/A

### Steps to reproduce the issue (if applicable)

I tried to reproduce in storybook but I think because this is coming through as a package import on our local code env, it can't really be that reproducible. 

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by AustinGitHub**
Closes #5526 

#### What did you change?

Fix condition check, see issue videos on why this condition check changed

#### How did you test and verify your work?

Story book, original use case still works. Won't know absolute fix until next version release since issue seems to be coming through due to how the importing of the component is happening.

### CODE REVIEW

File: packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.tsx [hunk 1]
```diff
@@ -299,7 +299,11 @@ export let DataSpreadsheet = React.forwardRef(
                   activeCellCoordinates?.column
                 ]
               : null;
-          setActiveCellContent(activeCellFullData?.render('Cell') ?? null);
+          if (activeCellFullData) {
```
Comment (AustinGitHub) [inline packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.tsx:302]: @matthewgallo Based on the videos here in the issue https://github.com/carbon-design-system/ibm-products/issues/5526 do you know if this is just a typescript issue? Because it looks like the null check originally does not work as intended when we import it through our packages on our code. I'm not that familiar with TypeScript outside the basics, not sure on the syntax specific differences there are. Can you let me know if you have any understanding? Thanks!

Would like to get this PR merged in as soon as possible if this is a true fix for what I am seeing on our local env. This is actually a regression in 2.40 for us though on storybook it wasn't able to be replicated, like I mentioned in the issue it looks like due to how it gets imported to the packages, the null checks get constructed weirdly. Thanks!

Comment (matthewgallo) [reply packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.tsx:302]: Sure, I'll take a look.

Comment (AustinGitHub) [reply packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.tsx:302]: I'll make a video and send it over on slack after lunch. Thanks!

**Review by matthewgallo — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me!
