### PR TITLE
fix(storybook): add fontBase

### LINKED ISSUE #6822: Update storybook theme to use `plex` so it can be applied to docs, left panel, etc.
We need to add a `fontBase` property to our storybook theme config in order for other storybook components also use `plex`. Currently the default storybook font (`Nunito Sans`) is used instead.

- [ ] Add `fontBase` to `packages/core/.storybook/manager.js` where we create the theme
- [ ] [Storybook theming docs](https://storybook.js.org/docs/configure/user-interface/theming) for reference

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #6822

Changed storybook font to IBM Plex sans. 

#### What did you change?
packages/core/.storybook/manager.js
packages/core/.storybook/theme.js
packages/core/.storybook/preview.js

### CODE REVIEW

**Review by paul-balchin-ibm — APPROVED** [review]
LGTM!

File: packages/core/.storybook/theme.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import { create } from '@storybook/theming/create';
+import packageInfo from '../../ibm-products/package.json';
+
+const { description, version } = packageInfo;
+
+console.log(description, version);
```
Comment (elycheea) [inline packages/core/.storybook/theme.js:6]:
```suggestion
```

Just one `console.log()` that snuck in. :)

**Review by davidmenendez — APPROVED** [review]

**Review by matthewgallo — APPROVED** [review]
