### PR TITLE
fix(tagset): updates props

### LINKED ISSUE #5703: TagSet: showAllTagsLabel should probably not be marked as required
### Package

Carbon for IBM Products

### Description

The PropTypes for TagSet's `allTagsModalSearchLabel`, `allTagsModalSearchPlaceholderText`, `allTagsModalTitle`, and `showAllTagsLabel` say that those attributes are required **if** there are more than 10 tags:

```js
export const string_required_if_more_than_10_tags = isRequiredIf(
  PropTypes.string,
  ({ tags }) => tags && tags.length > allTagsModalSearchThreshold
);

...

  /**
   * label text for the show all search. **Note: Required if more than 10 tags**
   */
  allTagsModalSearchLabel: string_required_if_more_than_10_tags,
  /**
   * placeholder text for the show all search. **Note: Required if more than 10 tags**
   */
  allTagsModalSearchPlaceholderText: string_required_if_more_than_10_tags,
...
  /**
   * title for the show all modal. **Note: Required if more than 10 tags**
   */
  allTagsModalTitle: string_required_if_more_than_10_tags,
...

  /**
   * label for the overflow show all tags link.
   *
   * **Note:** Required if more than 10 tags
   */
  showAllTagsLabel: string_required_if_more_than_10_tags,
```

AFAIK you can't write a complex condition like that in Typescript, so TagSet.d.ts' Typescript declarations should probably mark those attributes as optional.  And it does, except for `showAllTagsLabel`.  TagSet.d.ts says that `showAllTagsLabel` is required:

```ts
    /**
     * label text for the show all search. **Note: Required if more than 10 tags**
     */
    allTagsModalSearchLabel?: string;
    /**
     * placeholder text for the show all search. **Note: Required if more than 10 tags**
     */
    allTagsModalSearchPlaceholderText?: string;
...
    /**
     * title for the show all modal. **Note: Required if more than 10 tags**
     */
    allTagsModalTitle?: string;

...
    /**
     * label for the overflow show all tags link.
     *
     * **Note:** Required if more than 10 tags
     */
    showAllTagsLabel: string;
```

### Component(s) impacted

TagSet

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

None

### Product/offering

IKC

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-tag-set-tagset--docs

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by AlexanderMelox**
Closes #5703 

This PR updates the tagset props. The initial issue is to update the typescript prop but after investigating I realized that it's better to not force the user to add a prop after 10 tags but have defaults and give the user the option to update them if they want to change the text for the labels. 

#### What did you change?
- packages/ibm-products/src/components/TagSet/TagSet.tsx

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Review by davidmenendez — APPROVED** [review]

File: packages/ibm-products/src/components/TagSet/TagSet.tsx [hunk 1]
```diff
@@ -128,9 +121,9 @@ export interface TagSetProps extends PropsWithChildren {
   /**
    * label for the overflow show all tags link.
    *
-   * **Note:** Required if more than 10 tags
+   *  **Note: Required if more than 10 tags**
    */
-  showAllTagsLabel: string;
+  showAllTagsLabel?: string;
```
Comment (amal-k-joy) [inline packages/ibm-products/src/components/TagSet/TagSet.tsx:126]: Hey @AlexanderMelox ,
Approach looks good. 
But, where are we specifying the default label for `showAllTagsLabel`?

**Review by amal-k-joy — CHANGES_REQUESTED** [review]

File: packages/ibm-products/src/components/TagSet/TagSet.tsx (hunk 1 above)
Comment (AlexanderMelox) [reply packages/ibm-products/src/components/TagSet/TagSet.tsx:126]: @amal-k-joy so this was a good discussion because in the proptypes it is required if there are more than 10 tags present. There is currently no way to represent this logic with typescript types. Initially In this PR I tried to add default string parameters but it was making test run for ever and timeout, you can see it in [this commit ](https://github.com/carbon-design-system/ibm-products/pull/5962/commits/10a4663767afbf392d2ba6b73b9b172fedbc80b2)

```
 /**
   * label for the overflow show all tags link.
   *
   * **Note:** Required if more than 10 tags
   */
  showAllTagsLabel: string_required_if_more_than_10_tags,
```

Comment (AlexanderMelox) [reply packages/ibm-products/src/components/TagSet/TagSet.tsx:126]: @davidmenendez later found out that the default string params were okay but the `tags = []` was causing the issue. So I will be adding it back. Thanks @amal-k-joy

Comment (AlexanderMelox) [reply packages/ibm-products/src/components/TagSet/TagSet.tsx:126]: I removed requirements to add props after 10 tags or more and just added optional props and default strings. I think this is a better approach and we do this in other components anyways.

Comment (amal-k-joy) [reply packages/ibm-products/src/components/TagSet/TagSet.tsx:126]: Hey @AlexanderMelox , 
This feels like a better approach since it make more easier for adopters. But can we update this prop description as well  ? it still says the props as required.
image

**Review by amal-k-joy — CHANGES_REQUESTED** [review]

File: packages/ibm-products/src/components/TagSet/TagSet.tsx (hunk 1 above)
Comment (amal-k-joy) [reply packages/ibm-products/src/components/TagSet/TagSet.tsx:126]: Hi @AlexanderMelox ,
This feels like better approach since this make it more easier for users. 
One minor thing. Storybook props description need to be updated accordingly.

image

Comment (AlexanderMelox) [reply packages/ibm-products/src/components/TagSet/TagSet.tsx:124]: Done ✅  thank you for the feedback

**Review by amal-k-joy — APPROVED** [review]
Looking good, Thanks for the changes.

**Review by davidmenendez — APPROVED** [review]

**Comment by wkeese** [comment]
@AlexanderMelox - Thanks for fixing that!  You just forgot to remove the definition for `string_required_if_more_than_10_tags`, can you remove that too?
