### PR TITLE
fix: Resolve all typescript errors

### LINKED ISSUE #5945: TypeScript errors anywhere `ButtonProps[]` is used
### Package

Carbon for IBM Products

### Description

There are TypeScript errors anywhere in our library where `ButtonProps[]` is used. 

image

### Component(s) impacted

Components specifying `ButtonProps[]`

### Browser

_No response_

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

Latest

### Suggested Severity

None

### Product/offering

N/A

### CodeSandbox or Stackblitz example

N/A

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by makafsal**
Closes #5945 
This resolves many typescript issues including #5945 

#### What did you change?
Fixed typescript errors across all components

#### How did you test and verify your work?
`yarn avt`
`yarn test`

### CODE REVIEW

File: packages/ibm-products/src/components/CreateInfluencer/CreateInfluencer.tsx [hunk 1]
```diff
@@ -90,7 +90,7 @@ export const CreateInfluencer = ({
             {progressSteps.map((step, stepIndex) => {
```
Comment (AlexanderMelox) [inline packages/ibm-products/src/components/CreateInfluencer/CreateInfluencer.tsx:90]: Can we just type the props here to avoid using type casting?

File: packages/ibm-products/src/components/CreateModal/CreateModal.tsx [hunk 2]
```diff
@@ -61,7 +61,7 @@ export interface CreateModalProps
   /**
    * The title of the CreateModal is usually the product or service name.
    */
-  title: ReactNode;
+  title: string;
```
Comment (AlexanderMelox) [inline packages/ibm-products/src/components/CreateModal/CreateModal.tsx:64]: Wonder why we are changing this to string? normally titles follow a node so users can have more flexibility to add icons etc.

File: packages/ibm-products/src/components/CreateModal/CreateModal.tsx [hunk 3]
```diff
@@ -90,7 +90,7 @@ export interface CreateModalProps
   /**
    * Specifies which DOM element in the form should be focused.
    */
-  selectorPrimaryFocus: ReactNode;
+  selectorPrimaryFocus: string;
```
Comment (AlexanderMelox) [inline packages/ibm-products/src/components/CreateModal/CreateModal.tsx:93]: Same as above, why the shift to string?

File: packages/ibm-products/src/components/SearchBar/SearchBar.tsx [hunk 4]
```diff
@@ -199,7 +199,7 @@ export let SearchBar = React.forwardRef<HTMLFormElement, SearchBarProps>(
       >
         {scopes?.length ? (
           <MultiSelect
-            {...multiSelectProps}
+            {...(multiSelectProps as any)}
```
Comment (AlexanderMelox) [inline packages/ibm-products/src/components/SearchBar/SearchBar.tsx:202]: Let's try to avoid any here

**Review by AlexanderMelox — CHANGES_REQUESTED** [review]

File: packages/ibm-products/src/components/CreateModal/CreateModal.tsx (hunk 3 above)
Comment (makafsal) [reply packages/ibm-products/src/components/CreateModal/CreateModal.tsx:93]: Because in `ComposedModal`, the `selectorPrimaryFocus` property type is `string`.
[ComposedModal.tsx#L207](https://github.com/carbon-design-system/carbon/blob/72fb7c06809d0039807f09be07419a3fa7d2fbf9/packages/react/src/components/ComposedModal/ComposedModal.tsx#L207)

File: packages/ibm-products/src/components/Checklist/Checklist.tsx [hunk 5]
```diff
@@ -170,7 +170,7 @@ export let Checklist = React.forwardRef(
       theme = defaults.theme,
       title,
       toggleLabel = defaults.toggleLabel,
-      toggleLabelAlign = defaults.toggleLabelAlign,
+      toggleLabelAlign = 'top',
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/Checklist/Checklist.tsx:173]: We should remove `toggleLabelAlign` from the defaults object if we're not going to use it from there anymore.

File: packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.tsx [hunk 6]
```diff
@@ -152,7 +152,7 @@ export interface CreateTearsheetProps extends PropsWithChildren {
   /**
    * The main title of the tearsheet, displayed in the header area.
    */
-  title?: ReactNode;
+  title?: string;
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.tsx:155]: This should remain `ReactNode` from what I can tell. Sometimes people have more complex titles that require passing in a node rather than a string.

File: packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.tsx [hunk 7]
```diff
@@ -438,7 +438,7 @@ CreateTearsheet.propTypes = {
   /**
    * The main title of the tearsheet, displayed in the header area.
    */
-  title: PropTypes.node,
+  title: PropTypes.string,
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.tsx:441]: This should remain `ReactNode` from what I can tell. Sometimes people have more complex titles that require passing in a node rather than a string.

File: packages/ibm-products/src/components/EmptyStates/EmptyState.tsx [hunk 8]
```diff
@@ -44,7 +44,7 @@ interface EmptyStateProps {
   action?: {
     kind?: 'primary' | 'secondary' | 'tertiary';
     renderIcon?: CarbonIconType;
-    onClick?: ButtonProps['onClick'];
+    onClick?: ButtonProps<'button'>['onClick'];
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/EmptyStates/EmptyState.tsx:47]: For consistency, can you use `React.ElementType`? This is use elsewhere in the PR.

File: packages/ibm-products/src/custom-typings/index.d.ts [hunk 9]
```diff
@@ -4,7 +4,7 @@
  * This source code is licensed under the Apache-2.0 license found in the
  * LICENSE file in the root directory of this source tree.
  */
-
+// @ts-nocheck
```
Comment (matthewgallo) [inline packages/ibm-products/src/custom-typings/index.d.ts:7]: Just wondering, why we need this?

**Review by AlexanderMelox — APPROVED** [review]

File: packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx [hunk 10]
```diff
@@ -59,7 +59,7 @@ export interface TearsheetProps extends PropsWithChildren {
    *
    * See https://react.carbondesignsystem.com/?path=/docs/components-button--default#component-api
    */
-  actions?: ButtonProps<'button'>[];
+  actions: ButtonProps<React.ElementType>[];
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx:62]: `actions` shouldn't be required for tearsheets. Just wondering about this change

File: packages/ibm-products/src/components/UserProfileImage/UserProfileImage.tsx [hunk 11]
```diff
@@ -224,8 +218,9 @@ export let UserProfileImage = React.forwardRef<
           label={tooltipText}
           className={`${blockClass}__tooltip ${carbonPrefix}--icon-tooltip`}
         >
-          {/**@ts-ignore */}
-          <TooltipTrigger>{renderUserProfileImage()}</TooltipTrigger>
+          <TooltipTrigger className={''}>
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/UserProfileImage/UserProfileImage.tsx:221]: Can we remove `className` if we're not utilizing it here?

**Comment by AlexanderMelox** [comment]
@makafsal Mend security checks are failing 
https://github.com/carbon-design-system/ibm-products/pull/6013/checks?check_run_id=31597815601

File: packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx [hunk 12]
```diff
@@ -59,7 +59,7 @@ export interface TearsheetProps extends PropsWithChildren {
    *
    * See https://react.carbondesignsystem.com/?path=/docs/components-button--default#component-api
    */
-  actions?: ButtonProps<'button'>[];
+  actions?: ButtonProps<React.ElementType>[];
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx:62]: We need to extend this, so that `label` can be provided as well. Otherwise we see type errors because we expect data to be passed in to construct the actions.

**Review by matthewgallo — APPROVED** [review]

**Review by davidmenendez — APPROVED** [review]
