### PR TITLE
fix(Create tearsheets and modals): disable ability to submit form using the Enter key

### LINKED ISSUE #7866: [CreateFullPage]: Enter key reloads page
### Package

Carbon for IBM Products

### Description

**Problem:**
When there is only one input field wrapped in a form element, the browser will automatically opt into submit on enter. This leads to the page being reloaded. 
In our case, only the first step includes an input field for name, the following steps include textareas, buttons, stacked tearsheets etc., hence browser does reload for us. 

**Solution:**
```jsx
<Form ... onSubmit={e => e.preventDefault()}>
```

Beyond fixing this issue, going to the next step or requesting a submit on said behavior (if `submitDisabled` is false) could be a good addition. 

### Component(s) impacted

CreateFullPage

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.70.1

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IKC

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/jovial-field-vmnsj5?workspaceId=ws_Gn3L2JHAJFsxCKCvJwZQQL

### Steps to reproduce the issue (if applicable)

1. Focus 1st step's input field
2. Hit enter

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by paul-balchin-ibm**
Closes #7866

This fix disables this default behavior [W3 Section 8.2](https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2) "When there is only one single-line text input field in a form, the user agent 'should' accept Enter in that field as a request to submit the form."

You can see Storybook example here:
1. [Create Full Page With Step In Error State](https://ibm-products.carbondesignsystem.com/?path=/story/patterns-prebuilt-patterns-create-flows-createfullpage--create-full-page-with-step-in-error-state). Single input field reloads the page. 
    - Set focus on the input field, 
    - hit the Enter key, 
    - the page reloads. 
3. [Create Full Page With Header](https://ibm-products.carbondesignsystem.com/?path=/story/patterns-prebuilt-patterns-create-flows-createfullpage--create-full-page-with-header). Single input field _and other form elements on the page_ (button for the toggle component, checkbox) prevent a page reload. More form elements on steps 3 and 4 in this example also exist on the page, but are hidden from the user.
    - Set focus on the input field, 
    - hit the Enter key, 
    - nothing happens. 

The "Create" components (listed below) wrap a `<Form>` around all developer content across multiple steps. All content for all steps are rendered to the DOM, but only the content on a specific step is made visible to the user.

**Issues**

1. If there is a single input text field in one of these forms, then hitting the Enter key while that field has focus will, following HTML standards, submit the form. This applies even if there is a single input field across multiple steps.
5. The `<Form>` used in the components are for internal use only. It is a recommended practice in wrapping multiple form elements, and is not meant to be reachable by the developer.
6. For the purposes of the Create components listed below, only clicking the component's Submit button should trigger a form submission. This action is accessible via the `onRequestSubmit` prop.

**Solution**

Added an _onSubmit = preventDefault()_ to the forms for each component below.

#### What did you change?

```
CreateFullPage
CreateModal
CreateSidePanel
CreateTearSheet
CreateTearSheetNarrow
```

#### How did you test and verify your work?

- Storybook.

#### PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] ~Updated documentation and storybook examples~
- [ ] ~Wrote passing tests that cover this change~
- [ ] ~Addressed any impact on accessibility (a11y)~
- [x] Tested for cross-browser consistency (Chrome, Firefox)
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request](./CONTRIBUTING.md) section of
our contributing docs.

### CODE REVIEW

File: packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx [hunk 1]
```diff
@@ -33,7 +33,6 @@ import {
   useCreateComponentFocus,
   useCreateComponentStepChange,
   usePreviousValue,
-  useResetCreateComponent,
```
Comment (paul-balchin-ibm) [inline packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx:36]: Removed unused import.

**Comment by amal-k-joy** [comment]
@paul-balchin-ibm 
I was wondering , why this behaviour of getting submitted on Enter key, is not observed in our storybook ?

**Comment by paul-balchin-ibm** [comment]
> _why this behaviour ... is not observed in our storybook ?_

Thanks for bringing this up, @amal-k-joy, I should have included examples/links.

I've updated the **Description** above with links and explanations.

**Review by amal-k-joy — APPROVED** [review]
Nice way of documenting details 🎉

**Review by matthewgallo — APPROVED** [review]
