### PR TITLE
fix(sidePanel): resolve storybook doc page scroll issues

### LINKED ISSUE #6623: [SidePanel Storybook Doc]: Storybook doc page scroll issues
### Package

Carbon for IBM Products

### Description

From @sangeethababu9223 's [comment](https://github.com/carbon-design-system/ibm-products/pull/6554#issuecomment-2552939260) in the PR [6554](https://github.com/carbon-design-system/ibm-products/pull/6554)

1. Can't scroll the entire page while SidePanel is open in the preview container (Can be found in SlideOver)

https://github.com/user-attachments/assets/830b87b5-6e59-4db1-9661-6eed50d102f9

2. Horizontal scroll in the `SlideIn` preview container

https://github.com/user-attachments/assets/c7aeb436-c4d6-4b91-8d0e-0da85fa4c687

### Component(s) impacted

SidePanel storybook doc page

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.56.0-rc.0

### Suggested Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Product/offering

PAL

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-side-panel-sidepanel--docs#slide-in

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by makafsal**
Closes #6623

#### What did you change?
1. removed unwanted storybook containers
2. confirm whether it is storybook or not before setting `overflow: hidden` for `body`

#### How did you test and verify your work?
storybook

### CODE REVIEW

File: packages/ibm-products/src/components/SidePanel/SidePanel.tsx [hunk 1]
```diff
@@ -525,7 +525,9 @@ export let SidePanel = React.forwardRef(
         }
       };
       const bodyElement = document.body;
-      if (includeOverlay && open) {
+      const isStorybook = document.getElementById('storybook-sidepanel');
```
Comment (matthewgallo) [inline packages/ibm-products/src/components/SidePanel/SidePanel.tsx:528]: I think this logic should be kept outside of the actual component. Is there a way we can include this in the stories file?

**Review by amal-k-joy — APPROVED** [review]
LGTM

**Review by matthewgallo — CHANGES_REQUESTED** [review]
The `slideIn` panel doesn't work as expected with these changes because the element with `id` `ibm-products-page-content` was removed.

**Review by matthewgallo — APPROVED** [review]

**Review by amal-k-joy — APPROVED** [review]
