### PR TITLE
fix(EditInPlace): removes focus when pressing esc or enter key

### LINKED ISSUE #5852: EditInPlace keeps focused state when invalid but field is not actually focused on
### Package

Carbon for IBM Products

### Description

Normally, if you focus on the `EditInPlace` component to give input, the state of the component gets focused by adding class `c4p--edit-in-place--focused`, and when you click away (remove focus or focus on another component), the focused state is removed.

But when the component has invalid input and you click away, the EditInPlace component stays focused even when it's not actually focused anymore. The focused state should be removed when component is no longer focused on, regardless of the invalid state. 

### Component(s) impacted

EditInPlace component

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.46.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM Cloud Data Replication

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/serene-wave-nlgmk5

### Steps to reproduce the issue (if applicable)

Reproduced here: https://codesandbox.io/p/devbox/serene-wave-nlgmk5 

## Normal scenario

Not focused
Screenshot 2024-08-12 at 4 22 43 PM

Focused
Screenshot 2024-08-12 at 4 24 06 PM
^Clicking on EditInPlace component to edit, component is focused and `c4p--edit-in-place--focused` class is added. 

Remove focus
Screenshot 2024-08-12 at 4 26 58 PM
Clicking away from EditInPlace component to remove focus, and `c4p--edit-in-place--focused` class is removed.

## Bug scenario

Not focused
Starting with same scenario above with just "abc" input.. not focused on EditInPlace component.
Screenshot 2024-08-12 at 4 28 49 PM

Focused and create invalid scenario (add numbers)
Screenshot 2024-08-12 at 4 30 28 PM
^Clickin on EditInPlace component to edit, which focuses on the component and adds `c4p--edit-in-place--focused` class.
Then added "1" to input to go into invalid state. This additionally adds `c4p--edit-in-place--invalid` class.. Both classes exist now.

Remove focus
Screenshot 2024-08-12 at 4 33 30 PM
First, hit the Enter key to submit/save the changes (keeping the invalid value).
At this time, technically you are no longer focused on the EditInPlace component.. but click somewhere else anyways.
The component keeps both invalid and focused state, but really it's not focused anymore.
This screenshot seems like i am still focused on the EditInPlace component, but i'm not.. If i had other components on the page, i could be clicking and typing in other fields and this would still look like this. 

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by AlexanderMelox**
Closes #5852 

This PR removes the focus of the EditInPlace after pressing Enter or the Escape key.

#### What did you change?
`packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx`

#### How did you test and verify your work?
Modified storybook story to reflect the code sandbox props

https://github.com/user-attachments/assets/29621692-3efc-4c88-9293-6b49327c1fb5

### CODE REVIEW

File: packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx [hunk 1]
```diff
@@ -248,16 +248,21 @@ export let EditInPlace = forwardRef<HTMLDivElement, EditInplaceProps>(
       onCancelHandler();
     };
 
+    const removeFocus = () => {
```
Comment (amal-k-joy) [inline packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx:251]: Hey @AlexanderMelox ,
Changes look fine. Just one doubt.
 I could see on `escape` press,  `inputRef.current?.blur();` and `setFocused(false);` was already happening previously. Inside `escapeHandler`, they are setting `false` to `setFocused`. I was just wondering why this issue existed earlier on `Escape` key.

**Review by amal-k-joy — CHANGES_REQUESTED** [review]

File: packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx (hunk 1 above)
Comment (AlexanderMelox) [reply packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx:251]: Okay I see, I realized that the focused state was only being triggered on enter when canSave is true. But for consistency, I'm going to only do it on the removeFocus function to keep the code DRY

Comment (AlexanderMelox) [reply packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx:249]: Thank you!

**Review by makafsal — APPROVED** [review]

**Review by amal-k-joy — APPROVED** [review]
